#Auto-incremented by Gradle on 2026-06-08 02:14:51
#Mon Jun 08 02:14:51 GMT 2026
org.gradle.caching=true
android.nonTransitiveRClass=false
kotlin.incremental=true
org.gradle.daemon=true
VERSION_CODE=368
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding\=UTF-8
android.enableJetifier=true
android.useAndroidX=true
kotlin.incremental.usePreciseJavaTracking=true
ksp.incremental.log=false
kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process
ksp.incremental=true
systemProp.java.runtime.name=Android
kotlin.parallel.tasks.in.project=true
android.aapt2FromMavenOverride=/data/data/com.termux/files/usr/bin/aapt2
