#Auto-incremented by Gradle on 2026-01-15 01:03:43
#Thu Jan 15 01:03:43 GMT 2026
VERSION_CODE=146
android.aapt2FromMavenOverride=/data/data/com.termux/files/usr/bin/aapt2
android.enableJetifier=true
android.nonTransitiveRClass=false
android.useAndroidX=true
kotlin.code.style=official
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding\=UTF-8
