#Auto-incremented by Gradle on 2026-01-12 10:28:49
#Mon Jan 12 10:28:49 GMT 2026
VERSION_CODE=119
android.aapt2FromMavenOverride=/data/data/com.termux/files/usr/bin/aapt2
android.enableJetifier=true
android.nonTransitiveRClass=false
android.useAndroidX=true
kotlin.code.style=official
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding\=UTF-8
