package com.hyperwhisper.localization

object ArabicStrings : Strings {
    // App Info
    override val appName = "HyperWhisper"
    override val imeName = "لوحة مفاتيح HyperWhisper الصوتية"

    // Common Actions
    override val cancel = "إلغاء"
    override val save = "حفظ"
    override val delete = "حذف"
    override val edit = "تعديل"
    override val add = "إضافة"
    override val close = "إغلاق"
    override val back = "رجوع"
    override val copy = "نسخ"
    override val clear = "مسح"

    // Keyboard UI
    override val tapToSpeak = "انقر للتحدث"
    override val recording = "جارٍ التسجيل..."
    override val processing = "جارٍ المعالجة..."
    override val space = "مسافة"
    override val pasteLastTranscription = "لصق آخر نسخ (اضغط مطولاً: السجل)"
    override val pasteLastHold = "لصق آخر نسخ (اضغط مطولاً: السجل)"
    override val holdForHistory = "اضغط مطولاً للسجل"

    // Buttons
    override val switchKeyboard = "تبديل لوحة المفاتيح"
    override val helpAndAbout = "مساعدة ومعلومات"
    override val settings = "الإعدادات"
    override val viewLogs = "عرض السجلات"
    override val stopRecording = "إيقاف التسجيل"
    override val startRecording = "بدء التسجيل"

    // Walkie-Talkie Mode
    override val walkieTalkieModeEnabled = "تم تفعيل وضع الاتصال اللاسلكي. للخروج، انقر مرتين على الزر."
    override val normalModeEnabled = "تم تفعيل الوضع العادي. اضغط مطولاً لتفعيل وضع الاتصال اللاسلكي."
    override val walkieTalkieLongPressHint = "اضغط مطولاً لوضع الاتصال اللاسلكي"

    // Content Descriptions (for accessibility)
    override val switchKeyboardDesc = "تبديل لوحة المفاتيح"
    override val helpAndAboutDesc = "مساعدة ومعلومات"
    override val settingsDesc = "الإعدادات"
    override val viewLogsDesc = "عرض السجلات"
    override val cancelDesc = "إلغاء"
    override val enterDesc = "إدخال"

    // Language Selectors
    override val inputLanguageSpeech = "لغة الإدخال (الكلام)"
    override val outputLanguageTranslation = "لغة الإخراج (الترجمة)"
    override val autoDetect = "كشف تلقائي"
    override val searchLanguages = "بحث..."
    override val searchPlaceholder = "بحث..."
    override val noLanguagesFound = "لم يتم العثور على لغات"

    // Settings Screen
    override val settingsTitle = "إعدادات HyperWhisper"
    override val apiConfiguration = "تكوين API"
    override val apiProvider = "مزود API"
    override val baseUrl = "عنوان URL الأساسي"
    override val baseUrlHint = "يجب أن ينتهي بـ /"
    override val apiKey = "مفتاح API"
    override val apiKeyPlaceholder = "sk-..."
    override val modelId = "معرف النموذج"
    override val testConnection = "اختبار الاتصال"
    override val testingConnection = "جارٍ اختبار الاتصال..."
    override val resetToDefaults = "إعادة تعيين إلى الافتراضي"
    override val reset = "إعادة تعيين"
    override val saveAndCloseSettings = "حفظ وإغلاق الإعدادات"
    override val inputLanguageHintLabel = "تلميح لغة الإدخال"
    override val inputLanguageHintText = "استخدم فقط للكشف التلقائي (لغة الكلام)\nملاحظة: معظم النماذج تتجاهل هذا\n• whisper-1 والأشكال المختلفة: يتم تجاهله\n• distil-whisper-large-v3: يستخدمه"
    override val viewApiLogs = "عرض سجلات API"
    override val logsInfoTitle = "سجلات API والتشخيص"
    override val logsInfoDescription = "عرض سجلات مفصلة لاستدعاءات API وخطوات المعالجة والأخطاء. يتم مسح السجلات عند إعادة تشغيل التطبيق."

    // API Providers
    override val providerDescription = "اختر مزود تحويل الكلام إلى نص"

    // Voice Modes
    override val voiceModes = "أوضاع معالجة الصوت"
    override val selectMode = "اختر الوضع"
    override val addVoiceMode = "إضافة وضع صوتي"
    override val editVoiceMode = "تعديل وضع صوتي"
    override val deleteVoiceMode = "حذف الوضع"
    override val modeName = "اسم الوضع"
    override val systemPrompt = "موجه النظام"
    override val enterPrompt = "أدخل موجه النظام لهذا الوضع"

    // Default Voice Modes
    override val modeVerbatim = "حرفي"
    override val modeVerbatimPrompt = "نسخ الصوت كما هو منطوق بالضبط."
    override val modeFixGrammar = "إصلاح القواعد"
    override val modeFixGrammarPrompt = "نسخ هذا الصوت وإصلاح أي أخطاء نحوية وإملائية وعلامات ترقيم مع الحفاظ على المعنى والنبرة الأصلية."
    override val modePromptFormatter = "منسق المطالبة"
    override val modePromptFormatterPrompt = "إعادة صياغة إدخال المستخدم إلى موجه واضح وفعال مناسب لمعالجة LLM. تحسين الوضوح وإضافة السياق الضروري وهيكلته لفهم أمثل للذكاء الاصطناعي. الحفاظ على نية المستخدم مع جعلها أكثر دقة وقابلية للتنفيذ."
    override val modeLlmResponse = "استجابة LLM"
    override val modeLlmResponsePrompt = "المستخدم يطرح سؤالاً. قدم إجابة مباشرة وموجزة للسؤال دون أي تفسير أو سياق إضافي. أرجع الإجابة فقط."

    // Appearance Settings
    override val appearanceSettings = "المظهر"
    override val colorScheme = "نظام الألوان"
    override val useDynamicColor = "استخدام الألوان الديناميكية"
    override val useDynamicColorDesc = "مطابقة ألوان خلفية النظام"
    override val themeMode = "وضع السمة"
    override val darkMode = "الوضع الداكن"
    override val textSize = "حجم النص"
    override val fontFamily = "عائلة الخط"
    override val uiLanguage = "لغة الواجهة"

    // Dark Mode Options
    override val darkModeFollowSystem = "متابعة النظام"
    override val darkModeAlwaysLight = "فاتح دائماً"
    override val darkModeAlwaysDark = "داكن دائماً"

    // Advanced Settings
    override val advancedSettings = "متقدم"
    override val autoCopyToClipboard = "نسخ تلقائي إلى الحافظة"
    override val autoCopyToClipboardDesc = "نسخ النسخ تلقائياً"
    override val enableHistoryPanel = "تمكين لوحة السجل"
    override val enableHistoryPanelDesc = "اضغط مطولاً على زر اللصق لعرض السجل"

    // About Screen
    override val aboutHyperWhisper = "حول HyperWhisper"
    override val version = "الإصدار"
    override val versionCode = "الرمز"
    override val description = "HyperWhisper هو طريقة إدخال صوت إلى نص (لوحة مفاتيح) تستخدم واجهات برمجة تطبيقات متقدمة للتعرف على الكلام لتوفير نسخ سريع ودقيق. مصمم للمطورين والمستخدمين المتقدمين الذين يريدون تخصيص تجربة الإدخال الصوتي الخاصة بهم."
    override val features = "المميزات:"
    override val featuresList = "• مزود API قابل للتخصيص (OpenAI، Groq، OpenRouter، إلخ.)\n• أوضاع صوتية متعددة (حرفي، إصلاح القواعد، مهذب، إلخ.)\n• دعم لغات الإدخال والإخراج المختلفة\n• واجهة مستخدم حديثة ومستجيبة مبنية بـ Jetpack Compose"
    override val usageStatisticsAndCosts = "إحصائيات الاستخدام والتكاليف:"
    override val noUsageDataYet = "لا توجد بيانات استخدام حتى الآن. ابدأ باستخدام لوحة المفاتيح لرؤية الإحصائيات!"
    override val totalAudio = "إجمالي الصوت"
    override val estimatedTotalCost = "التكلفة الإجمالية المقدرة"
    override val modelBreakdown = "تفصيل النموذج:"
    override val inputTokens = "الإدخال"
    override val outputTokens = "الإخراج"
    override val totalTokens = "الإجمالي"
    override val audioBasedPricing = "التسعير على أساس الصوت (لا يتم تتبع الرموز)"
    override val costsEstimateNote = "* التكاليف تقديرية بناءً على أسعار API الحالية. قد تختلف التكاليف الفعلية."
    override val clearStatistics = "مسح الإحصائيات"

    // Logs Screen
    override val traceLogs = "سجلات التتبع"
    override val diagnosticLogs = "سجلات التشخيص"
    override val diagnosticLogsDesc = "تظهر هذه السجلات استدعاءات API وخطوات المعالجة والأخطاء. يتم مسح السجلات عند إعادة تشغيل التطبيق. يمكنك نسخها أو مسحها باستخدام الأزرار أعلاه."
    override val logsStoredAt = "السجلات مخزنة في"
    override val noLogsYet = "لا توجد سجلات حتى الآن.\nابدأ باستخدام لوحة المفاتيح لرؤية سجلات النشاط."
    override val copyLogs = "نسخ السجلات"
    override val clearLogs = "مسح السجلات"
    override val logsCopiedToClipboard = "تم نسخ السجلات إلى الحافظة"

    // Configuration Info
    override val currentConfiguration = "التكوين الحالي"
    override val provider = "المزود"
    override val transcriptionModel = "نموذج النسخ"
    override val postProcessingModel = "نموذج ما بعد المعالجة"
    override val postProcessingModelDesc = "gpt-4o-mini (للأوضاع غير الحرفية والترجمة)"
    override val none = "لا شيء"
    override val keepOriginal = "الاحتفاظ بالأصلي"
    override val notConfigured = "غير مكون"

    // Transcription History
    override val transcriptionHistory = "سجل النسخ"
    override val historyCount = "{count}/20"
    override val noHistoryYet = "لا يوجد سجل حتى الآن"
    override val clearAll = "مسح الكل"

    // Connection Test
    override val connectionTesting = "جارٍ اختبار الاتصال..."
    override val connectionSuccess = "نجح الاتصال! API يستجيب."
    override val connectionFailed = "فشل الاتصال"
    override val authenticationFailed = "فشلت المصادقة. تحقق من مفتاح API الخاص بك."
    override val endpointNotFound = "لم يتم العثور على نقطة النهاية. تحقق من عنوان URL الأساسي ومعرف النموذج."
    override val connectionTimeout = "انتهت مهلة الاتصال. تحقق من اتصالك بالإنترنت."
    override val sslError = "خطأ SSL/TLS. تحقق من عنوان URL لنقطة النهاية (https)."

    // Errors
    override val error = "خطأ"
    override val copyError = "نسخ الخطأ"
    override val openSettings = "فتح الإعدادات"
    override val dismiss = "إغلاق"
    override val errorConfigureApiKey = "يرجى تكوين مفتاح API في الإعدادات"
    override val errorNoModeSelected = "لم يتم اختيار وضع صوتي"
    override val errorRecordingFailed = "فشل التسجيل"
    override val errorNetworkFailed = "خطأ في الشبكة. يرجى التحقق من اتصالك."
    override val errorApiCall = "خطأ في API"
    override val errorPermissionMicrophone = "لم يتم منح إذن الميكروفون. يرجى تمكين الوصول إلى الميكروفون في إعدادات Android."
    override val errorMicrophoneInUse = "لا يمكن الوصول إلى الميكروفون. قد يكون قيد الاستخدام بواسطة تطبيق آخر."

    // Processing Info Toast
    override val translated = "تمت الترجمة إلى"
    override val twoStepProcessing = "معالجة من خطوتين"

    // Time units
    override val minutes = "د"
    override val seconds = "ث"

    // Input Field Information
    override val inputFieldType = "النوع"
    override val inputFieldApp = "التطبيق"
    override val inputFieldAction = "الإجراء"
    override val fieldTypeText = "نص"
    override val fieldTypeEmail = "بريد إلكتروني"
    override val fieldTypePassword = "كلمة مرور"
    override val fieldTypeNumber = "رقم"
    override val fieldTypePhone = "هاتف"
    override val fieldTypeUrl = "URL"
    override val fieldTypeMultiline = "متعدد الأسطر"
    override val fieldTypeUnknown = "غير معروف"
    override val actionNone = "لا شيء"
    override val actionDone = "تم"
    override val actionGo = "انتقال"
    override val actionSearch = "بحث"
    override val actionSend = "إرسال"
    override val actionNext = "التالي"
    override val actionPrevious = "السابق"

    // Usage Guide (About Screen)
    override val usageGuideTitle = "كيفية الاستخدام"
    override val voiceModesGuide = "الأوضاع الصوتية"
    override val voiceModeVerbatimDesc = "حرفي - نسخ دقيق كما يُنطق"
    override val voiceModeFixGrammarDesc = "إصلاح القواعد - يصحح القواعد والإملاء"
    override val voiceModePoliteDesc = "مهذب - يجعل الكلام احترافياً وودوداً"
    override val voiceModePromptFormatterDesc = "منسق المطالبة - يحسّن النص لمطالبات الذكاء الاصطناعي"
    override val voiceModeLlmResponseDesc = "استجابة LLM - احصل على إجابات مباشرة للأسئلة"
    override val voiceModeConfigurationDesc = "التكوين - تحكم في إعدادات التطبيق بالصوت"
    override val configurationModeTitle = "وضع التكوين"
    override val configurationModeDesc = "انتقل إلى وضع \"التكوين\" للتحكم في الإعدادات بالأوامر الصوتية. عندما تنطق أمراً، سترى مربع حوار تأكيد يوضح ما سيتغير."
    override val sampleVoiceCommandsTitle = "أمثلة على الأوامر الصوتية"
    override val sampleCommandLanguage = "\"غيّر لغة الإدخال إلى الإسبانية\" / \"ترجم إلى الفرنسية\""
    override val sampleCommandMode = "\"غيّر الوضع إلى حرفي\" / \"فعّل وضع إصلاح القواعد\""
    override val sampleCommandTheme = "\"انتقل إلى الوضع الداكن\" / \"استخدم السمة الفاتحة\" / \"اتبع سمة النظام\""
    override val sampleCommandHistory = "\"فعّل السجل\" / \"أوقف السجل\""
    override val sampleCommandDeveloper = "\"فعّل وضع المطور\" / \"أوقف وضع التقني\""
    override val sampleCommandInterface = "\"غيّر الواجهة إلى الروسية\" / \"اضبط لغة الواجهة على العربية\""
    override val sampleCommandExit = "\"اخرج من وضع التكوين\" / \"أوقف وضع الأوامر\""
    override val howItWorksTitle = "كيف يعمل"
    override val howItWorksStep1 = "1. اختر \"التكوين\" من محدد الوضع"
    override val howItWorksStep2 = "2. انقر على الميكروفون وانطق أمرك"
    override val howItWorksStep3 = "3. راجع التغيير في مربع حوار التأكيد"
    override val howItWorksStep4 = "4. انقر \"تطبيق التغيير\" للتأكيد أو \"إلغاء\" للرفض"
    override val howItWorksConfirmation = "بعد التأكيد، سترى إشعاراً بتحديث الإعداد."
    override val deleteButtonTitle = "زر الحذف"
    override val deleteButtonTap = "نقر - حذف حرف واحد (أو النص المحدد)"
    override val deleteButtonHold = "ضغط مطول - حذف متواصل"
    override val deleteButtonLongHold = "ضغط 5 ثوانٍ - حذف كل النص (يتحول الزر إلى أحمر)"
    override val languageSelectionTitle = "اختيار اللغة"
    override val languageSelectionDesc = "استخدم وضع التكوين لتغيير اللغات بدون استخدام اليدين، أو انقر على أزرار اللغات أسفل الميكروفون للاختيار من القائمة."

    // Settings categories
    override val categoryTranscriptionTitle = "النسخ النصي"
    override val categoryTranscriptionSubtitle = "المزود، النموذج، اللغات"
    override val categoryPostProcessingTitle = "المعالجة اللاحقة"
    override val categoryPostProcessingSubtitle = "LLM للتحويلات والترجمة"
    override val categoryLocalModelsTitle = "النماذج المحلية"
    override val categoryLocalModelsSubtitle = "تنزيل نماذج Whisper + Gemma على الجهاز"
    override val categoryVoiceModesTitle = "أوضاع الصوت"
    override val categoryVoiceModesSubtitle = "موجهات مخصصة للنسخ النصي"
    override val categoryKeyboardBehaviorTitle = "لوحة المفاتيح والسلوك"
    override val categoryKeyboardBehaviorSubtitle = "السجل، الحافظة، ملفات الصوت"
    override val categoryAppearanceTitle = "المظهر"
    override val categoryAppearanceSubtitle = "السمة، الخطوط، لغة الواجهة"
    override val categoryAdvancedTitle = "متقدم"
    override val categoryAdvancedSubtitle = "السجلات، التكاملات، التشخيص"
    override val categoryAboutTitle = "حول"
    override val categoryAboutSubtitle = "الاعتمادات، الترخيص، الإصدار"

    // About stats
    override val statsAudioTranscribedLabel = "الصوت المنسوخ"
    override val statsTextWrittenLabel = "النص المكتوب"
    override val statsTypingTimeSavedLabel = "وقت الكتابة الموفر تقريباً عند 200 حرفاً/الدقيقة"

    // Settings overflow + advanced detail
    override val settingsOverflowAbout = "حول"
    override val settingsOverflowExportSecrets = "تصدير الأسرار"
    override val settingsOverflowMoreDesc = "المزيد"
    override val settingsActivePrefix = "نشط: "
    override val settingsSecretsCopiedToast = "تم نسخ الأسرار إلى الحافظة"
    override val advancedApiLogsTitle = "سجلات استدعاءات API"
    override val advancedApiLogsDescription = "فحص طلبات النسخ/LLM الأخيرة"
    override val advancedProviderKeyHelpTitle = "مساعدة في مفتاح API للمزود"
    override val advancedProviderKeyHelpDescription = "كيفية الحصول على مفتاح API للمزود الحالي"
    override val advancedExportSecretsTitle = "تصدير الأسرار إلى الحافظة"
    override val advancedExportSecretsDescription = "ينسخ جميع مفاتيح ونقاط نهاية المزودين بصيغة JSON"

    // Appearance section
    override val appearanceSectionColorHeader = "اللون"
    override val appearanceDynamicColorTitle = "اللون الديناميكي"
    override val appearanceDynamicColorDescription = "مطابقة ألوان خلفية الشاشة (Material You)"
    override val appearanceSectionThemeHeader = "السمة"
    override val appearanceSectionTypographyHeader = "الطباعة"
    override val appearanceTextSizeLabel = "حجم النص"
    override val appearanceFontFamilyLabel = "عائلة الخط"
    override val appearanceSectionInterfaceLanguageHeader = "لغة الواجهة"

    // LLM config section
    override val llmLocalLlamacppHeader = "خادم llama.cpp HTTP المحلي"
    override val llmLocalLlamacppDescription = "ابدأ الخادم في Termux أولاً، ثم سيتصل به HyperWhisper عبر HTTP. يفترض الرابط الافتراضي إعدادات llama-server التلقائية على 127.0.0.1:8080."
    override val llmLocalLlamacppCommands = "Termux:  pkg install llama-cpp\n         llama-server -m /sdcard/LLM/<model>.gguf"
    override val llmLocalLlamacppModelHint = "يجب أن يطابق Model ID أدناه اسم النموذج الذي يبلغ عنه llama-server (عادةً اسم ملف GGUF بدون امتداد، أو ما تمرره إلى --alias)."
    override val llmLocalGemmaHeader = "MediaPipe LLM داخل التطبيق"
    override val llmLocalGemmaActiveModelPrefix = "النموذج: "
    override val llmLocalGemmaNoModelHint = "لم يتم تحديد نموذج Gemma. اختر ملف .bin محوّل لـ MediaPipe (litert-community على HuggingFace) من النسخ → محلي. لن يتم تحميل ملفات GGUF."
    override val llmLocalGemmaOnDeviceNote = "يعمل بالكامل على الجهاز. لا حاجة لخادم خارجي."
    override val llmConfigBaseUrlLabel = "الرابط الأساسي لـ LLM"
    override val llmConfigBaseUrlSupportingText = "نقطة نهاية API للمعالجة اللاحقة بـ LLM"
    override val llmConfigNoApiKeyRequired = "لا يلزم مفتاح API"
    override val llmConfigApiKeyLabel = "مفتاح API لـ LLM"
    override val llmConfigApiKeyPlaceholder = "أدخل مفتاح API لمزود LLM"
    override val llmConfigUseTranscriptionKey = "استخدم مفتاح هذا المزود من النسخ"
    override val llmConfigReuseKeyForTranscription = "إعادة استخدام هذا المفتاح لمزود النسخ"
    override val llmConfigModelInfoDesc = "معلومات نموذج LLM"
    override val llmConfigUsageInfo = "يُستخدم هذا الـ LLM للمعالجة اللاحقة (مهذب، عفوي، إلخ) والترجمة. لا يُستخدم في الوضع الحرفي."
    override val llmConfigTestPostProcessing = "اختبار المعالجة اللاحقة بنص نموذجي"
    override val llmConfigTestRunningPlaceholder = "إرسال نص نموذجي إلى LLM…"
    override val llmConfigDisabledNote = "المعالجة اللاحقة معطلة. ستتوفر النسخ الحرفية فقط."

    // Keyboard behavior section
    override val keyboardBehaviorHistoryHeader = "السجل"
    override val keyboardBehaviorEnableHistoryDescription = "اضغط مطولاً على زر اللصق لعرض النسخ الأخيرة"
    override val keyboardBehaviorUnlimitedHistoryTitle = "سجل غير محدود"
    override val keyboardBehaviorUnlimitedHistoryDescription = "الاحتفاظ بجميع النسخ (يستخدم مساحة تخزين أكبر)"
    override val keyboardBehaviorClipboardAudioHeader = "الحافظة والصوت"
    override val keyboardBehaviorAutoCopyDescription = "نسخ كل نسخة تلقائياً"
    override val keyboardBehaviorSaveAudioTitle = "حفظ الصوت الأصلي"
    override val keyboardBehaviorSaveAudioDescription = "تخزين التسجيلات للتشغيل وإعادة المعالجة"
    override val keyboardBehaviorKeyboardHeader = "لوحة المفاتيح"
    override val keyboardBehaviorShowSwitcherTitle = "إظهار محول لوحة المفاتيح"
    override val keyboardBehaviorShowSwitcherDescription = "زر لتبديل أسلوب الإدخال، بجوار محدد الوضع"
    override val keyboardBehaviorPerAppLayoutTitle = "ذاكرة التخطيط لكل تطبيق"
    override val keyboardBehaviorPerAppLayoutDescription = "استعادة آخر تخطيط استخدمته في كل تطبيق (مثلاً Code في Termux، Voice في WhatsApp)"
    override val keyboardBehaviorCodingAgentsHeader = "وكلاء البرمجة"
    override val keyboardBehaviorCodingAgentsDescription = "أضف لوحات أوامر سريعة لوكلاء CLI. يظهر كل وكيل مفعّل كوضع منفصل في قائمة أوضاع لوحة المفاتيح."
    override val keyboardBehaviorAgentDescriptionPrefix = "لوحة أوامر سريعة لـ "
    override val keyboardBehaviorDeveloperHeader = "المطوّر"
    override val keyboardBehaviorTechieModeTitle = "وضع التقنيين"
    override val keyboardBehaviorTechieModeDescription = "إظهار معلومات التشخيص وزر السجلات على لوحة المفاتيح"
    override val keyboardBehaviorMaxHistoryTitle = "الحد الأقصى لعناصر السجل"
    override val keyboardBehaviorMaxHistoryRange = "العدد المراد الاحتفاظ به (1–100)"

    // Selectors
    override val selectorFontLabel = "الخط"
    override val selectorLanguageLabel = "اللغة"
    override val selectorCustomModelTag = "نموذج مخصص"
    override val selectorFilterModelsLabel = "تصفية النماذج"
    override val selectorFreeFilterLabel = "مجاني"
    override val selectorNoMatchingModels = "لا توجد نماذج مطابقة"
    override val selectorLlmModelLabel = "نموذج LLM"
    override val selectorLlmProviderLabel = "مزود LLM للمعالجة اللاحقة"
    override val selectorProviderLabel = "اختر مزوداً"

    // Transcription section
    override val transcriptionTabCloud = "السحابة"
    override val transcriptionTabLocal = "محلي"
    override val transcriptionTestButton = "اختبار التفريغ"
    override val transcriptionTestingShort = "جارٍ الاختبار…"
    override val transcriptionPreparingTest = "جارٍ تحضير الاختبار…"
    override val transcriptionWorkingPlaceholder = "جارٍ العمل…"
    override val transcriptionTestSuccessLabel = "نجاح"
    override val transcriptionTestFailedLabel = "فشل"
    override val transcriptionTestReadyLabel = "جاهز"
    override val transcriptionTestLogCopied = "تم نسخ سجل الاختبار"
    override val transcriptionTestLogCopyDesc = "نسخ السجل"
    override val transcriptionTestLogDismissDesc = "إغلاق"
    override val transcriptionTestLogExpand = "توسيع السجلات"
    override val transcriptionTestLogCollapse = "طي السجلات"
    override val transcriptionCloudActiveText = "السحابة هي مصدر التفريغ النشط."
    override val transcriptionCloudInactiveText = "تم حفظ إعدادات السحابة لكنها غير نشطة. استخدمها لتجاوز النموذج المحلي."
    override val transcriptionSetCloudActive = "تفعيل السحابة"
    override val transcriptionFieldGroupModel = "النموذج"
    override val transcriptionApiKeyRequiredHint = "مطلوب"
    override val transcriptionApiKeyOptionalHint = "اختياري"
    override val transcriptionApiKeyHide = "إخفاء"
    override val transcriptionApiKeyShow = "إظهار"
    override val transcriptionHowToGetKey = "كيفية الحصول على مفتاح"
    override val transcriptionLanguagesHeader = "اللغات"
    override val transcriptionInputLanguageLabel = "لغة الإدخال"
    override val transcriptionInputLanguageSupporting = "اللغة المنطوقة (يدعم الكشف التلقائي)"
    override val transcriptionOutputLanguageLabel = "لغة الإخراج"
    override val transcriptionOutputLanguageSupporting = "ترجمة التفريغ (اتركه فارغاً للاحتفاظ بالأصل)"
    override val transcriptionApiEndpointLabel = "نقطة نهاية API"
    override val transcriptionRequiresApiKey = "يتطلب مفتاح API"
    override val transcriptionRequiresApiKeyDesc = "عطّله للخوادم المستضافة ذاتياً بدون مصادقة"
    override val transcriptionLocalActivePrefix = "Whisper المحلي نشط: "
    override val transcriptionLocalInactiveText = "اختر نموذجاً أدناه — انقر على «استخدم هذا النموذج» لجعله مصدر التفريغ النشط."
    override val transcriptionStorageAccessRequired = "مطلوب الوصول إلى التخزين"
    override val transcriptionStorageAccessDesc = "للعثور على النماذج في التنزيلات والمجلدات المشتركة الأخرى"
    override val transcriptionGrantAccess = "منح الوصول"
    override val transcriptionWhisperModelsHeader = "نماذج Whisper"
    override val transcriptionNoModelsFound = "لم يتم العثور على نماذج. ضع ملفات .bin أو .gguf في Downloads/Models."
    override val transcriptionRescan = "إعادة المسح"
    override val transcriptionRefreshAccess = "تحديث الوصول"
    override val transcriptionPerformanceHeader = "الأداء"
    override val transcriptionAutoDiscoverTitle = "الاكتشاف التلقائي"
    override val transcriptionAutoDiscoverDesc = "البحث في المجلدات الشائعة عن ملفات النماذج"
    override val transcriptionThreadsTitle = "خيوط المعالجة"
    override val transcriptionThreadsDesc = "أعلى = أسرع، استهلاك بطارية أكبر (1–16)"
    override val transcriptionVerifyIntegrityDesc = "التحقق من السلامة"
    override val transcriptionUseThisModel = "استخدم هذا النموذج"
    override val transcriptionActiveBadge = "نشط"

    // Voice mode dialogs
    override val dialogVoiceModeNamePlaceholder = "مثال: رسمي"
    override val dialogVoiceModePromptPlaceholder = "مثال: فرّغ النص واجعله رسمياً"

    // Language info dialog
    override val dialogInputLanguageBody = "يقدم هذا الإعداد تلميحاً لنموذج التعرف على الكلام حول اللغة المنطوقة. على الرغم من أن «الكشف التلقائي» يعمل جيداً في معظم الحالات، فإن تحديد لغة معينة يمكن أن يحسّن الدقة:"
    override val dialogInputLanguageBullet1 = "• للمتحدثين بلهجات قوية."
    override val dialogInputLanguageBullet2 = "• للغات أو اللهجات الأقل شيوعاً."
    override val dialogInputLanguageBullet3 = "• في البيئات الصاخبة."
    override val dialogInputLanguageFooter = "إذا كانت تفريغاتك غير دقيقة، فجرّب ضبط هذا الإعداد على لغتك الأم."

    // Logs info dialog
    override val dialogLogsInfoBody = "يسجّل HyperWhisper كل طلبات واستجابات API لأغراض التصحيح."
    override val dialogLogsInfoViewingHeader = "عرض السجلات:"
    override val dialogLogsInfoViewing1 = "• استخدم ADB: adb logcat | grep HyperWhisper"
    override val dialogLogsInfoViewing2 = "• ثبّت تطبيق logcat من Play Store"
    override val dialogLogsInfoViewing3 = "• فلتر حسب: ChatCompletionStrategy, VoiceRepository"
    override val dialogLogsInfoLoggedHeader = "المعلومات المسجلة:"
    override val dialogLogsInfoLogged1 = "• تفاصيل طلب API (URL، النموذج، الإرشادات)"
    override val dialogLogsInfoLogged2 = "• حالة ومحتوى الاستجابة"
    override val dialogLogsInfoLogged3 = "• استخدام الرموز (إدخال/إخراج/إجمالي)"
    override val dialogLogsInfoLogged4 = "• معلومات ملف الصوت"
    override val dialogLogsInfoLogged5 = "• رسائل الأخطاء والتتبع"
    override val dialogLogsInfoNote = "ملاحظة: تعرض السجلات أول 10 أحرف من مفاتيح API فقط."

    // Model info dialog
    override val dialogModelInfoTitle = "معلومات النموذج"
    override val dialogModelInfoProviderPrefix = "المزود: "
    override val dialogModelInfoSelectedModelLabel = "النموذج المحدد:"
    override val dialogModelInfoAvailableModelsLabel = "النماذج المتاحة:"

    // Provider key instructions dialog
    override val dialogProviderKeyTitle = "كيفية الحصول على مفتاح API"
    override val providerKeyOpenaiStep1 = "1. افتح هذه الصفحة:"
    override val providerKeyOpenaiStep2 = "2. اضغط Create new secret key."
    override val providerKeyOpenaiStep3 = "3. انسخ المفتاح (يبدأ بـ sk-) والصقه في حقل مفتاح API."
    override val providerKeyDeepgramStep1 = "1. افتح هذه الصفحة:"
    override val providerKeyDeepgramStep2 = "2. أنشئ/اختر مشروعاً وافتح API Keys."
    override val providerKeyDeepgramStep3 = "3. أنشئ مفتاحاً والصقه في حقل مفتاح API."
    override val providerKeyAssemblyStep1 = "1. افتح هذه الصفحة:"
    override val providerKeyAssemblyStep2 = "2. اذهب إلى API Keys."
    override val providerKeyAssemblyStep3 = "3. انسخ المفتاح والصقه في حقل مفتاح API."
    override val providerKeyGoogleCloudStep1 = "1. افتح هذه الصفحة:"
    override val providerKeyGoogleCloudStep2 = "2. فعّل Speech-to-Text API لمشروعك."
    override val providerKeyGoogleCloudStep3 = "3. أنشئ بيانات الاعتماد والصق المفتاح/الرمز في حقل مفتاح API."
    override val providerKeyAwsStep1 = "1. افتح وحدة تحكم AWS:"
    override val providerKeyAwsStep2 = "2. أنشئ مفتاح وصول IAM بأذونات Transcribe."
    override val providerKeyAwsStep3 = "3. استخدم تنسيق مفتاح البروكسي/البوابة في حقل مفتاح API."
    override val providerKeyAzureStep1 = "1. افتح هذه الصفحة:"
    override val providerKeyAzureStep2 = "2. أنشئ مورد Speech وافتح Keys and Endpoint."
    override val providerKeyAzureStep3 = "3. انسخ المفتاح واضبط نقطة النهاية ومفتاح API."
    override val providerKeyDeepseekStep1 = "1. افتح هذه الصفحة:"
    override val providerKeyDeepseekStep2 = "2. أنشئ مفتاح API."
    override val providerKeyDeepseekStep3 = "3. الصق المفتاح في حقل مفتاح API."
    override val providerKeyMistralStep1 = "1. افتح هذه الصفحة:"
    override val providerKeyMistralStep2 = "2. أنشئ مفتاح API جديداً."
    override val providerKeyMistralStep3 = "3. الصق المفتاح في حقل مفتاح API."
    override val providerKeyRevStep1 = "1. افتح هذه الصفحة:"
    override val providerKeyRevStep2 = "2. أنشئ حساباً وولّد رمز وصول."
    override val providerKeyRevStep3 = "3. الصق الرمز في حقل مفتاح API."
    override val providerKeyGroqStep1 = "1. افتح هذه الصفحة:"
    override val providerKeyGroqStep2 = "2. أنشئ مفتاح API."
    override val providerKeyGroqStep3 = "3. الصقه في حقل مفتاح API."
    override val providerKeyOpenrouterStep1 = "1. افتح هذه الصفحة:"
    override val providerKeyOpenrouterStep2 = "2. أنشئ مفتاحاً."
    override val providerKeyOpenrouterStep3 = "3. الصقه في حقل مفتاح API."
    override val providerKeyGeminiStep1 = "1. افتح هذه الصفحة:"
    override val providerKeyGeminiStep2 = "2. أنشئ مفتاح API."
    override val providerKeyGeminiStep3 = "3. الصقه في حقل مفتاح API."
    override val providerKeyAntigravityStep1 = "1. استخدم وصول Google OAuth لإعادة استخدام الحصة المتاحة."
    override val providerKeyAntigravityStep2 = "2. اضبط Base URL على نقطة نهاية Antigravity."
    override val providerKeyAntigravityStep3 = "3. أبقِ مفتاح API معطلاً ما لم تتطلبه بوابتك."
    override val providerKeyHuggingfaceStep1 = "1. افتح هذه الصفحة:"
    override val providerKeyHuggingfaceStep2 = "2. أنشئ رمز وصول."
    override val providerKeyHuggingfaceStep3 = "3. الصق الرمز في حقل مفتاح API."
    override val providerKeySelfhostedStep1 = "1. شغّل خادم whisper.cpp محلياً أو عن بُعد."
    override val providerKeySelfhostedStep2 = "2. ضع عنوان الخادم في Base URL (للمحلي افتراضياً استخدم http://127.0.0.1:8080/)."
    override val providerKeySelfhostedStep3 = "3. إذا كانت المصادقة مفعّلة على بوابتك، الصق الرمز في حقل مفتاح API."
    override val providerKeyLocalStep1 = "1. لا تتطلب المعالجة المحلية مفتاح API."
    override val providerKeyLocalStep2 = "2. نزّل نموذج whisper.cpp (.bin) وضعه على جهازك."
    override val providerKeyLocalStep3 = "3. اذهب إلى قسم «النماذج المحلية» لمسح وتحديد ملف النموذج."

    // History reduction dialog
    override val dialogHistoryReductionTitle = "تقليل حجم السجل؟"
    override val dialogHistoryReductionBodyFormat = "أنت تقلل الحد الأقصى لحجم السجل من %1\$d إلى %2\$d عناصر."
    override val dialogHistoryReductionWarningFormat = "سيتم حذف %1\$d عناصر من السجل بما فيها ملفات الصوت بشكل نهائي."
    override val dialogHistoryReductionUndoNote = "لا يمكن التراجع عن هذا الإجراء."
    override val dialogHistoryReductionConfirmFormat = "حذف %1\$d عناصر"

    // API call logs screen
    override val apiCallLogsHeader = "سجلات استدعاءات API"
    override val apiCallLogsSubtitle = "عرض استدعاءات API الأخيرة"
    override val apiCallLogsStatistics = "الإحصائيات"
    override val apiCallLogsStatTotal = "إجمالي الاستدعاءات"
    override val apiCallLogsStatSuccess = "نجاح"
    override val apiCallLogsStatErrors = "أخطاء"
    override val apiCallLogsStatAvgTime = "متوسط الوقت"
    override val apiCallLogsEmpty = "لا توجد استدعاءات API مسجلة بعد"
    override val apiCallLogsErrorPrefix = "خطأ: "
    override val apiCallLogsSuccessDesc = "نجاح"
    override val apiCallLogsErrorDesc = "خطأ"

    // Language selector
    override val languageSelectorSearchPlaceholder = "بحث عن اللغات..."

    // Keyboard accessibility & top strip
    override val keyboardDictationDesc = "إملاء"
    override val keyboardBackspaceDesc = "حذف للخلف"
    override val keyboardEnterDesc = "إدخال"
    override val keyboardSearchDesc = "بحث"
    override val keyboardClearDesc = "مسح"
    override val keyboardBackToVoiceDesc = "العودة إلى الصوت"
    override val keyboardLogsDesc = "السجلات"
    override val keyboardHelpDesc = "مساعدة"

    // Emoji keyboard
    override val emojiNoEmojisFound = "لم يتم العثور على رموز تعبيرية"
    override val emojiRecentlyUsed = "المستخدمة مؤخراً"
    override val emojiSearchPlaceholder = "بحث عن رمز تعبيري..."

    // Enum: LlmProvider displayName
    override val providerLlmNone = "بدون (نسخ حرفي فقط)"
    override val providerLlmOpenai = "OpenAI"
    override val providerLlmDeepseek = "DeepSeek"
    override val providerLlmGemini = "Google Gemini"
    override val providerLlmAnthropic = "Anthropic Claude"
    override val providerLlmMistral = "Mistral AI"
    override val providerLlmGroq = "Groq"
    override val providerLlmOpenrouter = "OpenRouter"
    override val providerLlmOpenaiCompatible = "متوافق مع OpenAI"
    override val providerLlmLocalGemma = "Gemma محلي"
    override val providerLlmLocalLlamacpp = "خادم llama.cpp محلي"

    // Enum: ApiProvider displayName
    override val providerApiOpenai = "OpenAI Whisper"
    override val providerApiDeepgram = "Deepgram"
    override val providerApiAssemblyai = "AssemblyAI"
    override val providerApiGoogleCloud = "Google Cloud Speech"
    override val providerApiAwsTranscribe = "AWS Transcribe"
    override val providerApiAzureSpeech = "Azure AI Speech"
    override val providerApiDeepseek = "DeepSeek"
    override val providerApiMistral = "Mistral Voxtral"
    override val providerApiRevai = "Rev.ai"
    override val providerApiGroq = "Groq Whisper"
    override val providerApiOpenrouter = "OpenRouter"
    override val providerApiGemini = "Google Gemini"
    override val providerApiAntigravity = "Google Antigravity (OAuth)"
    override val providerApiHuggingface = "Hugging Face"
    override val providerApiSelfhostedWhisper = "Whisper مستضاف ذاتيًا"
    override val providerApiLocalWhisper = "Whisper محلي (.bin)"

    // Enum: ProcessingStage displayName
    override val processingStagePreparing = "تحضير الصوت..."
    override val processingStageConvertingAudio = "تحويل الصوت..."
    override val processingStageLoadingModel = "تحميل النموذج..."
    override val processingStageTranscribing = "النسخ..."
    override val processingStagePostProcessing = "معالجة لاحقة..."
    override val processingStageUploading = "رفع الصوت..."
    override val processingStageWaitingApi = "بانتظار الـ API..."
    override val processingStageFinishing = "الإنهاء..."

    // Enum: ColorSchemeOption displayName
    override val themeTerminalDark = "طرفية داكنة"
    override val themeOceanDeep = "أعماق المحيط"
    override val themeForestNight = "ليل الغابة"
    override val themeSunsetHorizon = "أفق الغروب"
    override val themeArcticFrost = "صقيع القطب"
    override val themeDesertStorm = "عاصفة الصحراء"
    override val themeNeonCity = "مدينة النيون"
    override val themeCherryBlossom = "زهر الكرز"
    override val themeMidnightSky = "سماء منتصف الليل"
    override val themeLavaFlow = "تدفق الحمم"
    override val themeMistyMountain = "الجبل الضبابي"
    override val themeAutumnLeaves = "أوراق الخريف"
    override val themeProfessionalBlue = "أزرق احترافي"
    override val themeWarmEarth = "أرض دافئة"
    override val themeCoolSlate = "أردواز بارد"
    override val themeVibrantPurple = "بنفسجي زاهٍ"
    override val themeEmeraldGreen = "أخضر زمردي"
    override val themeRubyRed = "أحمر ياقوتي"

    // Enum: UIScaleOption displayName
    override val uiScaleVerySmall = "صغير جدًا"
    override val uiScaleSmall = "صغير"
    override val uiScaleMedium = "متوسط"
    override val uiScaleLarge = "كبير"
    override val uiScaleVeryLarge = "كبير جدًا"

    // Enum: FontFamilyOption displayName
    override val fontFamilyDefault = "افتراضي"
    override val fontFamilySerif = "مذيّل"
    override val fontFamilySansSerif = "غير مذيّل"
    override val fontFamilyMonospace = "ثابت العرض"
    override val fontFamilyCursive = "متصل"

    // Enum: KeyboardInputMode displayName
    override val keyboardModeDictation = "صوت"
    override val keyboardModeQwerty = "نص"
    override val keyboardModeCode = "كود"
    override val keyboardModeEmoji = "رموز تعبيرية"
    override val keyboardModeAgentClaudeCode = "Claude Code"
    override val keyboardModeAgentOpencode = "OpenCode"
    override val keyboardModeAgentGemini = "Gemini CLI"
    override val keyboardModeAgentCodex = "Codex CLI"
    override val keyboardModeSpecialChars = "رموز"
    override val keyboardModeSystemKeys = "مفاتيح النظام"
    override val keyboardModeVibeCoding = "Vibe Coding"
    override val keyboardModeNumpad = "لوحة أرقام"

    // Enum: KeyboardLayout displayName
    override val keyboardLayoutEnglish = "الإنجليزية"
    override val keyboardLayoutRussian = "الروسية"
    override val keyboardLayoutSpanish = "الإسبانية"
    override val keyboardLayoutFrench = "الفرنسية"
    override val keyboardLayoutGerman = "الألمانية"
    override val keyboardLayoutArabic = "العربية"

    // Enum: EmojiCategory displayName
    override val emojiCategorySmileys = "وجوه مبتسمة"
    override val emojiCategoryPeople = "أشخاص"
    override val emojiCategoryAnimals = "حيوانات"
    override val emojiCategoryFood = "طعام"
    override val emojiCategoryActivities = "أنشطة"
    override val emojiCategoryTravel = "سفر"
    override val emojiCategoryObjects = "أشياء"
    override val emojiCategorySymbols = "رموز"
    override val emojiCategoryFlags = "أعلام"

    // Processing indicator
    override val processingEstimatedTimeFormat = "تقريباً: ~%d ث"

    // Network errors
    override val errorForbidden = "ممنوع — تحقق من صلاحيات المفتاح."
    override val errorRateLimit = "تم تجاوز حد الطلبات — حاول مرة أخرى قريباً."
    override val errorUnknown = "خطأ غير معروف"
    override val errorProcessingFailedFormat = "فشل المعالجة: %1\$s: %2\$s"

    // Local processing
    override val secretsGateRevealTitle = "أكّد لعرض مفتاح API"
    override val secretsGateExportTitle = "أكّد لتصدير الأسرار"
    override val secretsGateSubtitle = "استخدم قفل الجهاز للمتابعة"
    override val secretsGateNotEnrolledMessage = "قم بإعداد قفل الجهاز للمتابعة"
    override val secretsGateUnavailableMessage = "مصادقة الجهاز غير متاحة"

    override val errorLocalWhisperPathMissing = "لم يتم تكوين مسار نموذج Whisper المحلي."
    override val errorLocalWhisperModelNotFoundFormat = "لم يتم العثور على نموذج Whisper المحلي في: %s"
    override val errorLocalWhisperEmptyResult = "لم يُعد Whisper المحلي أي نص. جرب نموذجاً مختلفاً أو صوتاً أعلى."
    override val errorLocalProcessingFailedFormat = "فشلت المعالجة المحلية: %1\$s: %2\$s"
    override val errorLocalInferenceFailedFormat = "فشل الاستدلال المحلي: %1\$s: %2\$s"
}
