package com.hyperwhisper.localization

object EnglishStrings : Strings {
    // App Info
    override val appName = "HyperWhisper"
    override val imeName = "HyperWhisper Voice Keyboard"

    // Common Actions
    override val cancel = "Cancel"
    override val save = "Save"
    override val delete = "Delete"
    override val edit = "Edit"
    override val add = "Add"
    override val close = "Close"
    override val back = "Back"
    override val copy = "Copy"
    override val clear = "Clear"

    // Keyboard UI
    override val tapToSpeak = "Tap to speak"
    override val recording = "Recording..."
    override val processing = "Processing..."
    override val space = "space"
    override val pasteLastTranscription = "PASTE LAST (hold: history)"
    override val pasteLastHold = "PASTE LAST (hold: history)"
    override val holdForHistory = "Hold for history"

    // Buttons
    override val switchKeyboard = "Switch Keyboard"
    override val helpAndAbout = "Help & About"
    override val settings = "Settings"
    override val viewLogs = "View Logs"
    override val stopRecording = "Stop Recording"
    override val startRecording = "Start Recording"

    // Walkie-Talkie Mode
    override val walkieTalkieModeEnabled = "Walkie-Talkie mode enabled. To exit, double-tap the button."
    override val normalModeEnabled = "Normal mode enabled. Long press to activate Walkie-Talkie mode."
    override val walkieTalkieLongPressHint = "Long press for Walkie-Talkie mode"

    // Content Descriptions (for accessibility)
    override val switchKeyboardDesc = "Switch Keyboard"
    override val helpAndAboutDesc = "Help & About"
    override val settingsDesc = "Settings"
    override val viewLogsDesc = "View Logs"
    override val cancelDesc = "Cancel"
    override val enterDesc = "Enter"

    // Language Selectors
    override val inputLanguageSpeech = "Input Language (Speech)"
    override val outputLanguageTranslation = "Output Language (Translation)"
    override val autoDetect = "Auto-detect"
    override val searchLanguages = "Search..."
    override val searchPlaceholder = "Search..."
    override val noLanguagesFound = "No languages found"

    // Settings Screen
    override val settingsTitle = "HyperWhisper Settings"
    override val apiConfiguration = "API Configuration"
    override val apiProvider = "API Provider"
    override val baseUrl = "Base URL"
    override val baseUrlHint = "Must end with /"
    override val apiKey = "API Key"
    override val apiKeyPlaceholder = "sk-..."
    override val modelId = "Model ID"
    override val testConnection = "Test Connection"
    override val testingConnection = "Testing connection..."
    override val resetToDefaults = "Reset to Defaults"
    override val reset = "RESET"
    override val saveAndCloseSettings = "Save & Close Settings"
    override val inputLanguageHintLabel = "Input Language Hint"
    override val inputLanguageHintText = "Only use for auto-detect (speech language)\nNote: Most models ignore this\n• whisper-1 & variants: Ignored\n• distil-whisper-large-v3: Uses it"
    override val viewApiLogs = "View API Logs"
    override val logsInfoTitle = "API & Diagnostic Logs"
    override val logsInfoDescription = "View detailed logs of API calls, processing steps, and errors. Logs are cleared on app restart."

    // API Providers
    override val providerDescription = "Choose your speech-to-text provider"

    // Voice Modes
    override val voiceModes = "Voice Processing Modes"
    override val selectMode = "Select Mode"
    override val addVoiceMode = "Add Voice Mode"
    override val editVoiceMode = "Edit Voice Mode"
    override val deleteVoiceMode = "Delete Mode"
    override val modeName = "Mode Name"
    override val systemPrompt = "System Prompt"
    override val enterPrompt = "Enter the system prompt for this mode"

    // Default Voice Modes
    override val modeVerbatim = "Verbatim"
    override val modeVerbatimPrompt = "Transcribe the audio exactly as spoken."
    override val modeFixGrammar = "Fix Grammar"
    override val modeFixGrammarPrompt = "Transcribe this audio and fix any grammar, spelling, and punctuation errors while preserving the original meaning and tone."
    override val modePromptFormatter = "Prompt Formatter"
    override val modePromptFormatterPrompt = "Reformulate the user's input into a clear, effective prompt suitable for LLM processing. Enhance clarity, add necessary context, and structure it for optimal AI understanding. Maintain the user's intent while making it more precise and actionable."
    override val modeLlmResponse = "LLM Response"
    override val modeLlmResponsePrompt = "The user is asking a question. Provide a direct, concise answer to the question without any additional explanation or context. Return ONLY the answer itself."

    // Appearance Settings
    override val appearanceSettings = "Appearance"
    override val colorScheme = "Color Scheme"
    override val useDynamicColor = "Use Dynamic Color"
    override val useDynamicColorDesc = "Match system wallpaper colors"
    override val themeMode = "Theme Mode"
    override val darkMode = "Dark Mode"
    override val textSize = "Text Size"
    override val fontFamily = "Font Family"
    override val uiLanguage = "Interface Language"

    // Dark Mode Options
    override val darkModeFollowSystem = "Follow System"
    override val darkModeAlwaysLight = "Always Light"
    override val darkModeAlwaysDark = "Always Dark"

    // Advanced Settings
    override val advancedSettings = "Advanced"
    override val autoCopyToClipboard = "Auto-copy to Clipboard"
    override val autoCopyToClipboardDesc = "Automatically copy transcriptions"
    override val enableHistoryPanel = "Enable History Panel"
    override val enableHistoryPanelDesc = "Long-press paste button to view history"

    // About Screen
    override val aboutHyperWhisper = "About HyperWhisper"
    override val version = "Version"
    override val versionCode = "Code"
    override val description = "HyperWhisper is a voice-to-text input method (keyboard) that uses advanced speech recognition APIs to provide fast and accurate transcriptions. It is designed for developers and power users who want to customize their voice input experience."
    override val features = "Features:"
    override val featuresList = "• Customizable API provider (OpenAI, Groq, OpenRouter, etc.)\n• Multiple voice modes (Verbatim, Grammar Fix, Polite, etc.)\n• Support for different input and output languages\n• Modern, responsive UI built with Jetpack Compose"
    override val usageStatisticsAndCosts = "Usage Statistics & Costs:"
    override val noUsageDataYet = "No usage data yet. Start using the keyboard to see statistics!"
    override val totalAudio = "Total Audio"
    override val estimatedTotalCost = "Estimated Total Cost"
    override val modelBreakdown = "Model Breakdown:"
    override val inputTokens = "Input"
    override val outputTokens = "Output"
    override val totalTokens = "Total"
    override val audioBasedPricing = "Audio-based pricing (tokens not tracked)"
    override val costsEstimateNote = "* Costs are estimated based on current API pricing. Actual costs may vary."
    override val clearStatistics = "CLEAR STATISTICS"

    // Logs Screen
    override val traceLogs = "Trace Logs"
    override val diagnosticLogs = "Diagnostic Logs"
    override val diagnosticLogsDesc = "These logs show API calls, processing steps, and errors. Logs are cleared on app restart. You can copy or clear them using the buttons above."
    override val logsStoredAt = "Logs are stored in"
    override val noLogsYet = "No logs yet.\nStart using the keyboard to see activity logs."
    override val copyLogs = "Copy Logs"
    override val clearLogs = "Clear Logs"
    override val logsCopiedToClipboard = "Logs copied to clipboard"

    // Configuration Info
    override val currentConfiguration = "Current Configuration"
    override val provider = "Provider"
    override val transcriptionModel = "Transcription Model"
    override val postProcessingModel = "Post-Processing Model"
    override val postProcessingModelDesc = "gpt-4o-mini (for non-verbatim modes & translation)"
    override val none = "None"
    override val keepOriginal = "keep original"
    override val notConfigured = "Not configured"

    // Transcription History
    override val transcriptionHistory = "Transcription History"
    override val historyCount = "{count}/20"
    override val noHistoryYet = "No history yet"
    override val clearAll = "CLEAR ALL"

    // Connection Test
    override val connectionTesting = "Testing connection..."
    override val connectionSuccess = "Connection successful! API is responding."
    override val connectionFailed = "Connection failed"
    override val authenticationFailed = "Authentication failed. Check your API key."
    override val endpointNotFound = "Endpoint not found. Check base URL and model ID."
    override val connectionTimeout = "Connection timeout. Check your internet connection."
    override val sslError = "SSL/TLS error. Check endpoint URL (https)."

    // Errors
    override val error = "Error"
    override val copyError = "COPY ERROR"
    override val openSettings = "OPEN SETTINGS"
    override val dismiss = "DISMISS"
    override val errorConfigureApiKey = "Please configure API key in settings"
    override val errorNoModeSelected = "No voice mode selected"
    override val errorRecordingFailed = "Recording failed"
    override val errorNetworkFailed = "Network error. Please check your connection."
    override val errorApiCall = "API Error"
    override val errorPermissionMicrophone = "Microphone permission not granted. Please enable microphone access in Android Settings."
    override val errorMicrophoneInUse = "Cannot access microphone. It may be in use by another app."

    // Processing Info Toast
    override val translated = "Translated to"
    override val twoStepProcessing = "Two-step processing"

    // Time units
    override val minutes = "m"
    override val seconds = "s"

    // Input Field Information
    override val inputFieldType = "Type"
    override val inputFieldApp = "App"
    override val inputFieldAction = "Action"
    override val fieldTypeText = "Text"
    override val fieldTypeEmail = "Email"
    override val fieldTypePassword = "Password"
    override val fieldTypeNumber = "Number"
    override val fieldTypePhone = "Phone"
    override val fieldTypeUrl = "URL"
    override val fieldTypeMultiline = "Multiline"
    override val fieldTypeUnknown = "Unknown"
    override val actionNone = "None"
    override val actionDone = "Done"
    override val actionGo = "Go"
    override val actionSearch = "Search"
    override val actionSend = "Send"
    override val actionNext = "Next"
    override val actionPrevious = "Previous"

    // Usage Guide (About Screen)
    override val usageGuideTitle = "How to Use"
    override val voiceModesGuide = "Voice Modes"
    override val voiceModeVerbatimDesc = "Verbatim - Exact transcription as spoken"
    override val voiceModeFixGrammarDesc = "Fix Grammar - Corrects grammar and spelling"
    override val voiceModePoliteDesc = "Polite - Makes speech professional and friendly"
    override val voiceModePromptFormatterDesc = "Prompt Formatter - Optimizes text for AI prompts"
    override val voiceModeLlmResponseDesc = "LLM Response - Get direct answers to questions"
    override val voiceModeConfigurationDesc = "Configuration - Control app settings by voice"
    override val configurationModeTitle = "Configuration Mode"
    override val configurationModeDesc = "Switch to \"Configuration\" mode to control settings by voice commands. When you speak a command, you'll see a confirmation dialog showing what will change."
    override val sampleVoiceCommandsTitle = "Sample Voice Commands"
    override val sampleCommandLanguage = "\"Change input language to Spanish\" / \"Translate to French\""
    override val sampleCommandMode = "\"Change mode to verbatim\" / \"Enable fix grammar mode\""
    override val sampleCommandTheme = "\"Switch to dark mode\" / \"Use light theme\" / \"Follow system theme\""
    override val sampleCommandHistory = "\"Enable history\" / \"Turn off history\""
    override val sampleCommandDeveloper = "\"Enable developer mode\" / \"Turn off techie mode\""
    override val sampleCommandInterface = "\"Change interface to Russian\" / \"Set UI language to Arabic\""
    override val sampleCommandExit = "\"Exit configuration mode\" / \"Turn off command mode\""
    override val howItWorksTitle = "How it works"
    override val howItWorksStep1 = "1. Select \"Configuration\" from the mode selector"
    override val howItWorksStep2 = "2. Tap the microphone and speak your command"
    override val howItWorksStep3 = "3. Review the change in the confirmation dialog"
    override val howItWorksStep4 = "4. Tap \"Apply Change\" to confirm or \"Cancel\" to dismiss"
    override val howItWorksConfirmation = "After confirmation, you'll see a notification that the setting was updated."
    override val deleteButtonTitle = "Delete Button"
    override val deleteButtonTap = "Tap - Delete one character (or selected text)"
    override val deleteButtonHold = "Hold - Repeat delete continuously"
    override val deleteButtonLongHold = "Hold 5 seconds - Delete ALL text (button turns red)"
    override val languageSelectionTitle = "Language Selection"
    override val languageSelectionDesc = "Use Configuration mode to change languages hands-free, or tap the language buttons below the microphone to select from the list."

    // Settings categories
    override val categoryTranscriptionTitle = "Transcription"
    override val categoryTranscriptionSubtitle = "Provider, model, languages"
    override val categoryPostProcessingTitle = "Post-processing"
    override val categoryPostProcessingSubtitle = "LLM for transforms & translation"
    override val categoryLocalModelsTitle = "Local models"
    override val categoryLocalModelsSubtitle = "Download Whisper + Gemma models on-device"
    override val categoryVoiceModesTitle = "Voice Modes"
    override val categoryVoiceModesSubtitle = "Custom prompts for transcriptions"
    override val categoryKeyboardBehaviorTitle = "Keyboard & Behavior"
    override val categoryKeyboardBehaviorSubtitle = "History, clipboard, audio files"
    override val categoryAppearanceTitle = "Appearance"
    override val categoryAppearanceSubtitle = "Theme, fonts, interface language"
    override val categoryAdvancedTitle = "Advanced"
    override val categoryAdvancedSubtitle = "Logs, integrations, diagnostics"
    override val categoryAboutTitle = "About"
    override val categoryAboutSubtitle = "Credits, license, version"

    // About stats
    override val statsAudioTranscribedLabel = "Audio transcribed"
    override val statsTextWrittenLabel = "Text written"
    override val statsTypingTimeSavedLabel = "Approx typing time saved at 200 cpm"

    // Settings overflow + advanced detail
    override val settingsOverflowAbout = "About"
    override val settingsOverflowExportSecrets = "Export secrets"
    override val settingsOverflowMoreDesc = "More"
    override val settingsActivePrefix = "Active: "
    override val settingsSecretsCopiedToast = "Secrets copied to clipboard"
    override val advancedApiLogsTitle = "API call logs"
    override val advancedApiLogsDescription = "Inspect recent transcription/LLM requests"
    override val advancedProviderKeyHelpTitle = "Provider API key help"
    override val advancedProviderKeyHelpDescription = "How to get an API key for the current provider"
    override val advancedExportSecretsTitle = "Export secrets to clipboard"
    override val advancedExportSecretsDescription = "Copies all provider keys & endpoints as JSON"

    // Appearance section
    override val appearanceSectionColorHeader = "Color"
    override val appearanceDynamicColorTitle = "Dynamic color"
    override val appearanceDynamicColorDescription = "Match your wallpaper colors (Material You)"
    override val appearanceSectionThemeHeader = "Theme"
    override val appearanceSectionTypographyHeader = "Typography"
    override val appearanceTextSizeLabel = "Text size"
    override val appearanceFontFamilyLabel = "Font family"
    override val appearanceSectionInterfaceLanguageHeader = "Interface language"

    // LLM config section
    override val llmLocalLlamacppHeader = "Local llama.cpp HTTP server"
    override val llmLocalLlamacppDescription = "Start the server in Termux first, then HyperWhisper hits it over HTTP. Default URL assumes llama-server's zero-config 127.0.0.1:8080."
    override val llmLocalLlamacppCommands = "Termux:  pkg install llama-cpp\n         llama-server -m /sdcard/LLM/<model>.gguf"
    override val llmLocalLlamacppModelHint = "Model ID below must match llama-server's reported model name (usually the GGUF file stem, or whatever you pass to --alias)."
    override val llmLocalGemmaHeader = "In-process MediaPipe LLM"
    override val llmLocalGemmaActiveModelPrefix = "Model: "
    override val llmLocalGemmaNoModelHint = "No Gemma model selected. Pick a MediaPipe-converted .bin (litert-community on HuggingFace) under Transcription → Local. GGUF files won't load."
    override val llmLocalGemmaOnDeviceNote = "Runs entirely on-device. No external server needed."
    override val llmConfigBaseUrlLabel = "LLM Base URL"
    override val llmConfigBaseUrlSupportingText = "API endpoint for post-processing LLM"
    override val llmConfigNoApiKeyRequired = "No API key required"
    override val llmConfigApiKeyLabel = "LLM API Key"
    override val llmConfigApiKeyPlaceholder = "Enter API key for LLM provider"
    override val llmConfigUseTranscriptionKey = "Use this provider's key from Transcription"
    override val llmConfigReuseKeyForTranscription = "Reuse this key for transcription provider"
    override val llmConfigModelInfoDesc = "LLM Model Info"
    override val llmConfigUsageInfo = "This LLM is used for post-processing (polite, casual, etc.) and translation. Not used in verbatim mode."
    override val llmConfigTestPostProcessing = "Test post-processing with sample text"
    override val llmConfigTestRunningPlaceholder = "Sending sample text to LLM…"
    override val llmConfigDisabledNote = "Post-processing disabled. Only verbatim transcription will be available."

    // Keyboard behavior section
    override val keyboardBehaviorHistoryHeader = "History"
    override val keyboardBehaviorEnableHistoryDescription = "Long-press paste button to view recent transcriptions"
    override val keyboardBehaviorUnlimitedHistoryTitle = "Unlimited history"
    override val keyboardBehaviorUnlimitedHistoryDescription = "Keep all transcriptions (uses more storage)"
    override val keyboardBehaviorClipboardAudioHeader = "Clipboard & audio"
    override val keyboardBehaviorAutoCopyDescription = "Copy each transcription automatically"
    override val keyboardBehaviorSaveAudioTitle = "Save original audio"
    override val keyboardBehaviorSaveAudioDescription = "Store recordings for playback and reprocessing"
    override val keyboardBehaviorKeyboardHeader = "Keyboard"
    override val keyboardBehaviorShowSwitcherTitle = "Show keyboard switcher"
    override val keyboardBehaviorShowSwitcherDescription = "Button to switch input method, next to mode selector"
    override val keyboardBehaviorPerAppLayoutTitle = "Per-app layout memory"
    override val keyboardBehaviorPerAppLayoutDescription = "Restore the last layout you used in each app (e.g. Code in Termux, Voice in WhatsApp)"
    override val keyboardBehaviorCodingAgentsHeader = "Coding agents"
    override val keyboardBehaviorCodingAgentsDescription = "Add quick-command keyboards for CLI agents. Each enabled agent appears as a separate mode in the keyboard's mode dropdown."
    override val keyboardBehaviorAgentDescriptionPrefix = "Quick-command keyboard for "
    override val keyboardBehaviorDeveloperHeader = "Developer"
    override val keyboardBehaviorTechieModeTitle = "Techie mode"
    override val keyboardBehaviorTechieModeDescription = "Show diagnostic info and logs button on the keyboard"
    override val keyboardBehaviorMaxHistoryTitle = "Maximum history items"
    override val keyboardBehaviorMaxHistoryRange = "Number to keep (1–100)"

    // Selectors
    override val selectorFontLabel = "Font"
    override val selectorLanguageLabel = "Language"
    override val selectorCustomModelTag = "Custom model"
    override val selectorFilterModelsLabel = "Filter models"
    override val selectorFreeFilterLabel = "Free"
    override val selectorNoMatchingModels = "No matching models"
    override val selectorLlmModelLabel = "LLM Model"
    override val selectorLlmProviderLabel = "Post-Processing LLM Provider"
    override val selectorProviderLabel = "Select Provider"

    // Transcription section
    override val transcriptionTabCloud = "Cloud"
    override val transcriptionTabLocal = "Local"
    override val transcriptionTestButton = "Test transcription"
    override val transcriptionTestingShort = "Testing…"
    override val transcriptionPreparingTest = "Preparing test…"
    override val transcriptionWorkingPlaceholder = "Working…"
    override val transcriptionTestSuccessLabel = "Success"
    override val transcriptionTestFailedLabel = "Failed"
    override val transcriptionTestLogCopied = "Test log copied"
    override val transcriptionTestLogCopyDesc = "Copy log"
    override val transcriptionTestLogDismissDesc = "Dismiss"
    override val transcriptionCloudActiveText = "Cloud is the active transcription source."
    override val transcriptionCloudInactiveText = "Cloud configuration saved but not active. Use this to override the on-device model."
    override val transcriptionSetCloudActive = "Set cloud as active"
    override val transcriptionFieldGroupModel = "Model"
    override val transcriptionApiKeyRequiredHint = "Required"
    override val transcriptionApiKeyOptionalHint = "Optional"
    override val transcriptionApiKeyHide = "Hide"
    override val transcriptionApiKeyShow = "Show"
    override val transcriptionHowToGetKey = "How to get a key"
    override val transcriptionLanguagesHeader = "Languages"
    override val transcriptionInputLanguageLabel = "Input language"
    override val transcriptionInputLanguageSupporting = "Spoken language (auto-detect supported)"
    override val transcriptionOutputLanguageLabel = "Output language"
    override val transcriptionOutputLanguageSupporting = "Translate transcription (leave blank to keep original)"
    override val transcriptionApiEndpointLabel = "API endpoint"
    override val transcriptionRequiresApiKey = "Requires API key"
    override val transcriptionRequiresApiKeyDesc = "Disable for self-hosted servers without auth"
    override val transcriptionLocalActivePrefix = "On-device Whisper is active: "
    override val transcriptionLocalInactiveText = "Pick a model below — tap “Use this model” to make it the active transcription source."
    override val transcriptionStorageAccessRequired = "Storage access required"
    override val transcriptionStorageAccessDesc = "To find models in Downloads and other shared folders"
    override val transcriptionGrantAccess = "Grant access"
    override val transcriptionWhisperModelsHeader = "Whisper models"
    override val transcriptionNoModelsFound = "No models found. Place .bin or .gguf files in Downloads/Models."
    override val transcriptionRescan = "Rescan"
    override val transcriptionRefreshAccess = "Refresh access"
    override val transcriptionPerformanceHeader = "Performance"
    override val transcriptionAutoDiscoverTitle = "Auto-discover"
    override val transcriptionAutoDiscoverDesc = "Scan common folders for model files"
    override val transcriptionThreadsTitle = "Processing threads"
    override val transcriptionThreadsDesc = "Higher = faster, more battery (1–16)"
    override val transcriptionVerifyIntegrityDesc = "Verify integrity"
    override val transcriptionUseThisModel = "Use this model"
    override val transcriptionActiveBadge = "Active"

    // Voice mode dialogs
    override val dialogVoiceModeNamePlaceholder = "e.g., Formal"
    override val dialogVoiceModePromptPlaceholder = "e.g., Transcribe and make it formal"

    // Language info dialog
    override val dialogInputLanguageBody = "This setting provides a hint to the speech recognition model about the language being spoken. While 'Auto-detect' works well in most cases, providing a specific language can improve accuracy:"
    override val dialogInputLanguageBullet1 = "• For speakers with strong accents."
    override val dialogInputLanguageBullet2 = "• For less common languages or dialects."
    override val dialogInputLanguageBullet3 = "• In noisy environments."
    override val dialogInputLanguageFooter = "If your transcriptions are inaccurate, try setting this to your native language."

    // Logs info dialog
    override val dialogLogsInfoBody = "HyperWhisper logs all API requests and responses for debugging."
    override val dialogLogsInfoViewingHeader = "Viewing Logs:"
    override val dialogLogsInfoViewing1 = "• Use ADB: adb logcat | grep HyperWhisper"
    override val dialogLogsInfoViewing2 = "• Install a logcat app from Play Store"
    override val dialogLogsInfoViewing3 = "• Filter by: ChatCompletionStrategy, VoiceRepository"
    override val dialogLogsInfoLoggedHeader = "Logged Information:"
    override val dialogLogsInfoLogged1 = "• API request details (URL, model, prompts)"
    override val dialogLogsInfoLogged2 = "• Response status and content"
    override val dialogLogsInfoLogged3 = "• Token usage (input/output/total)"
    override val dialogLogsInfoLogged4 = "• Audio file information"
    override val dialogLogsInfoLogged5 = "• Error messages and traces"
    override val dialogLogsInfoNote = "Note: Logs show first 10 chars of API keys only."

    // Model info dialog
    override val dialogModelInfoTitle = "Model Information"
    override val dialogModelInfoProviderPrefix = "Provider: "
    override val dialogModelInfoSelectedModelLabel = "Selected Model:"
    override val dialogModelInfoAvailableModelsLabel = "Available Models:"

    // Provider key instructions dialog
    override val dialogProviderKeyTitle = "How to get API key"
    override val providerKeyOpenaiStep1 = "1. Open this page:"
    override val providerKeyOpenaiStep2 = "2. Click Create new secret key."
    override val providerKeyOpenaiStep3 = "3. Copy key (starts with sk-) and paste into API Key."
    override val providerKeyDeepgramStep1 = "1. Open this page:"
    override val providerKeyDeepgramStep2 = "2. Create/select project and open API Keys."
    override val providerKeyDeepgramStep3 = "3. Create key and paste it into API Key."
    override val providerKeyAssemblyStep1 = "1. Open this page:"
    override val providerKeyAssemblyStep2 = "2. Go to API Keys."
    override val providerKeyAssemblyStep3 = "3. Copy key and paste into API Key."
    override val providerKeyGoogleCloudStep1 = "1. Open this page:"
    override val providerKeyGoogleCloudStep2 = "2. Enable Speech-to-Text API for your project."
    override val providerKeyGoogleCloudStep3 = "3. Create credentials and paste key/token into API Key."
    override val providerKeyAwsStep1 = "1. Open AWS Console:"
    override val providerKeyAwsStep2 = "2. Create IAM access key with Transcribe permissions."
    override val providerKeyAwsStep3 = "3. Use your proxy/gateway key format in API Key field."
    override val providerKeyAzureStep1 = "1. Open this page:"
    override val providerKeyAzureStep2 = "2. Create Speech resource and open Keys and Endpoint."
    override val providerKeyAzureStep3 = "3. Copy key and set endpoint + API Key."
    override val providerKeyDeepseekStep1 = "1. Open this page:"
    override val providerKeyDeepseekStep2 = "2. Create an API key."
    override val providerKeyDeepseekStep3 = "3. Paste the key into API Key."
    override val providerKeyMistralStep1 = "1. Open this page:"
    override val providerKeyMistralStep2 = "2. Create a new API key."
    override val providerKeyMistralStep3 = "3. Paste the key into API Key."
    override val providerKeyRevStep1 = "1. Open this page:"
    override val providerKeyRevStep2 = "2. Create account and generate access token."
    override val providerKeyRevStep3 = "3. Paste token into API Key."
    override val providerKeyGroqStep1 = "1. Open this page:"
    override val providerKeyGroqStep2 = "2. Create API key."
    override val providerKeyGroqStep3 = "3. Paste into API Key."
    override val providerKeyOpenrouterStep1 = "1. Open this page:"
    override val providerKeyOpenrouterStep2 = "2. Create key."
    override val providerKeyOpenrouterStep3 = "3. Paste into API Key."
    override val providerKeyGeminiStep1 = "1. Open this page:"
    override val providerKeyGeminiStep2 = "2. Create API key."
    override val providerKeyGeminiStep3 = "3. Paste into API Key."
    override val providerKeyAntigravityStep1 = "1. Use Google OAuth-backed access to reuse available quota."
    override val providerKeyAntigravityStep2 = "2. Configure Base URL to the Antigravity endpoint."
    override val providerKeyAntigravityStep3 = "3. Keep API key disabled unless your gateway requires one."
    override val providerKeyHuggingfaceStep1 = "1. Open this page:"
    override val providerKeyHuggingfaceStep2 = "2. Create access token."
    override val providerKeyHuggingfaceStep3 = "3. Paste token into API Key."
    override val providerKeySelfhostedStep1 = "1. Start a local or remote whisper.cpp server."
    override val providerKeySelfhostedStep2 = "2. Put server URL into Base URL (for local default use http://127.0.0.1:8080/)."
    override val providerKeySelfhostedStep3 = "3. If auth is enabled on your gateway, paste token into API Key."
    override val providerKeyLocalStep1 = "1. Local processing does not require an API key."
    override val providerKeyLocalStep2 = "2. Download a whisper.cpp model (.bin) and place it on your device."
    override val providerKeyLocalStep3 = "3. Go to 'Local Models' section to scan and select the model file."

    // History reduction dialog
    override val dialogHistoryReductionTitle = "Reduce History Size?"
    override val dialogHistoryReductionBodyFormat = "You are reducing the maximum history size from %1\$d to %2\$d items."
    override val dialogHistoryReductionWarningFormat = "%1\$d history items including their audio files will be permanently deleted."
    override val dialogHistoryReductionUndoNote = "This action cannot be undone."
    override val dialogHistoryReductionConfirmFormat = "DELETE %1\$d ITEMS"

    // API call logs screen
    override val apiCallLogsHeader = "API CALL LOGS"
    override val apiCallLogsSubtitle = "View recent API calls"
    override val apiCallLogsClearDesc = "Clear Logs"
    override val apiCallLogsStatistics = "Statistics"
    override val apiCallLogsStatTotal = "Total Calls"
    override val apiCallLogsStatSuccess = "Success"
    override val apiCallLogsStatErrors = "Errors"
    override val apiCallLogsStatAvgTime = "Avg Time"
    override val apiCallLogsEmpty = "No API calls logged yet"
    override val apiCallLogsErrorPrefix = "Error: "
    override val apiCallLogsSuccessDesc = "Success"
    override val apiCallLogsErrorDesc = "Error"

    // Language selector
    override val languageSelectorSearchPlaceholder = "Search languages..."

    // Keyboard accessibility & top strip
    override val keyboardDictationDesc = "Dictation"
    override val keyboardBackspaceDesc = "Backspace"
    override val keyboardEnterDesc = "Enter"
    override val keyboardSearchDesc = "Search"
    override val keyboardClearDesc = "Clear"
    override val keyboardBackToVoiceDesc = "Back to voice"
    override val keyboardLogsDesc = "Logs"
    override val keyboardHelpDesc = "Help"

    // Emoji keyboard
    override val emojiNoEmojisFound = "No emojis found"
    override val emojiRecentlyUsed = "Recently Used"
    override val emojiSearchPlaceholder = "Search emoji..."
}
