package com.hyperwhisper.localization

object RussianStrings : Strings {
    // App Info
    override val appName = "HyperWhisper"
    override val imeName = "HyperWhisper Голосовая Клавиатура"

    // Common Actions
    override val cancel = "Отмена"
    override val save = "Сохранить"
    override val delete = "Удалить"
    override val edit = "Редактировать"
    override val add = "Добавить"
    override val close = "Закрыть"
    override val back = "Назад"
    override val copy = "Копировать"
    override val clear = "Очистить"

    // Keyboard UI
    override val tapToSpeak = "Нажмите для записи"
    override val recording = "Запись..."
    override val processing = "Обработка..."
    override val space = "пробел"
    override val pasteLastTranscription = "ВСТАВИТЬ ПОСЛЕДНЮЮ (удержать: история)"
    override val pasteLastHold = "ВСТАВИТЬ ПОСЛЕДНЮЮ (удержать: история)"
    override val holdForHistory = "Удержать для истории"

    // Buttons
    override val switchKeyboard = "Сменить клавиатуру"
    override val helpAndAbout = "Справка и О программе"
    override val settings = "Настройки"
    override val viewLogs = "Показать логи"
    override val stopRecording = "Остановить запись"
    override val startRecording = "Начать запись"

    // Walkie-Talkie Mode
    override val walkieTalkieModeEnabled = "Режим рации включен. Для выхода дважды нажмите кнопку."
    override val normalModeEnabled = "Обычный режим включен. Удерживайте для активации режима рации."
    override val walkieTalkieLongPressHint = "Удерживайте для режима рации"

    // Content Descriptions (for accessibility)
    override val switchKeyboardDesc = "Сменить клавиатуру"
    override val helpAndAboutDesc = "Справка и О программе"
    override val settingsDesc = "Настройки"
    override val viewLogsDesc = "Показать логи"
    override val cancelDesc = "Отмена"
    override val enterDesc = "Ввод"

    // Language Selectors
    override val inputLanguageSpeech = "Язык ввода (речь)"
    override val outputLanguageTranslation = "Язык вывода (перевод)"
    override val autoDetect = "Авто-определение"
    override val searchLanguages = "Поиск..."
    override val searchPlaceholder = "Поиск..."
    override val noLanguagesFound = "Языки не найдены"

    // Settings Screen
    override val settingsTitle = "Настройки HyperWhisper"
    override val apiConfiguration = "Настройка API"
    override val apiProvider = "Провайдер API"
    override val baseUrl = "Базовый URL"
    override val baseUrlHint = "Должен заканчиваться на /"
    override val apiKey = "Ключ API"
    override val apiKeyPlaceholder = "sk-..."
    override val modelId = "ID модели"
    override val testConnection = "Проверить соединение"
    override val testingConnection = "Проверка соединения..."
    override val resetToDefaults = "Сбросить к настройкам по умолчанию"
    override val reset = "СБРОСИТЬ"
    override val saveAndCloseSettings = "Сохранить и закрыть настройки"
    override val inputLanguageHintLabel = "Подсказка языка ввода"
    override val inputLanguageHintText = "Используйте только для авто-определения (язык речи)\nПримечание: Большинство моделей игнорирует это\n• whisper-1 и варианты: Игнорируется\n• distil-whisper-large-v3: Использует"
    override val viewApiLogs = "Показать логи API"
    override val logsInfoTitle = "Логи API и диагностики"
    override val logsInfoDescription = "Просмотр подробных логов вызовов API, этапов обработки и ошибок. Логи очищаются при перезапуске приложения."

    // API Providers
    override val providerDescription = "Выберите провайдера распознавания речи"

    // Voice Modes
    override val voiceModes = "Режимы обработки голоса"
    override val selectMode = "Выберите режим"
    override val addVoiceMode = "Добавить голосовой режим"
    override val editVoiceMode = "Редактировать голосовой режим"
    override val deleteVoiceMode = "Удалить режим"
    override val modeName = "Название режима"
    override val systemPrompt = "Системный промпт"
    override val enterPrompt = "Введите системный промпт для этого режима"

    // Default Voice Modes
    override val modeVerbatim = "Точная копия"
    override val modeVerbatimPrompt = "Расшифровать аудио точно как произнесено."
    override val modeFixGrammar = "Исправить грамматику"
    override val modeFixGrammarPrompt = "Расшифровать это аудио и исправить любые грамматические, орфографические ошибки и пунктуацию, сохраняя исходный смысл и тон."
    override val modePromptFormatter = "Форматировщик промптов"
    override val modePromptFormatterPrompt = "Переформулировать ввод пользователя в четкий, эффективный промпт, подходящий для обработки LLM. Улучшить ясность, добавить необходимый контекст и структурировать для оптимального понимания ИИ. Сохранить намерение пользователя, делая его более точным и действенным."
    override val modeLlmResponse = "Ответ LLM"
    override val modeLlmResponsePrompt = "Пользователь задает вопрос. Предоставить прямой, краткий ответ на вопрос без дополнительных объяснений или контекста. Вернуть ТОЛЬКО сам ответ."

    // Appearance Settings
    override val appearanceSettings = "Внешний вид"
    override val colorScheme = "Цветовая схема"
    override val useDynamicColor = "Использовать динамические цвета"
    override val useDynamicColorDesc = "Соответствовать цветам обоев системы"
    override val themeMode = "Режим темы"
    override val darkMode = "Темный режим"
    override val textSize = "Размер текста"
    override val fontFamily = "Семейство шрифтов"
    override val uiLanguage = "Язык интерфейса"

    // Dark Mode Options
    override val darkModeFollowSystem = "Следовать системе"
    override val darkModeAlwaysLight = "Всегда светлый"
    override val darkModeAlwaysDark = "Всегда темный"

    // Advanced Settings
    override val advancedSettings = "Дополнительно"
    override val autoCopyToClipboard = "Авто-копирование в буфер"
    override val autoCopyToClipboardDesc = "Автоматически копировать расшифровки"
    override val enableHistoryPanel = "Включить панель истории"
    override val enableHistoryPanelDesc = "Длительное нажатие кнопки вставки для просмотра истории"

    // About Screen
    override val aboutHyperWhisper = "О HyperWhisper"
    override val version = "Версия"
    override val versionCode = "Код"
    override val description = "HyperWhisper — это метод ввода голос-в-текст (клавиатура), который использует передовые API распознавания речи для обеспечения быстрой и точной расшифровки. Разработан для разработчиков и опытных пользователей, желающих настроить свой голосовой ввод."
    override val features = "Возможности:"
    override val featuresList = "• Настраиваемый провайдер API (OpenAI, Groq, OpenRouter и др.)\n• Несколько голосовых режимов (Точная копия, Исправление грамматики, Вежливый и др.)\n• Поддержка различных языков ввода и вывода\n• Современный, отзывчивый интерфейс на Jetpack Compose"
    override val usageStatisticsAndCosts = "Статистика использования и затраты:"
    override val noUsageDataYet = "Данных об использовании пока нет. Начните использовать клавиатуру, чтобы увидеть статистику!"
    override val totalAudio = "Всего аудио"
    override val estimatedTotalCost = "Приблизительная общая стоимость"
    override val modelBreakdown = "Разбивка по моделям:"
    override val inputTokens = "Ввод"
    override val outputTokens = "Вывод"
    override val totalTokens = "Всего"
    override val audioBasedPricing = "Ценообразование на основе аудио (токены не отслеживаются)"
    override val costsEstimateNote = "* Затраты оцениваются на основе текущих цен API. Фактические затраты могут отличаться."
    override val clearStatistics = "ОЧИСТИТЬ СТАТИСТИКУ"

    // Logs Screen
    override val traceLogs = "Журналы трассировки"
    override val diagnosticLogs = "Диагностические журналы"
    override val diagnosticLogsDesc = "Эти журналы показывают вызовы API, этапы обработки и ошибки. Журналы очищаются при перезапуске приложения. Вы можете скопировать или очистить их с помощью кнопок выше."
    override val logsStoredAt = "Журналы хранятся в"
    override val noLogsYet = "Журналов пока нет.\nНачните использовать клавиатуру, чтобы увидеть журналы активности."
    override val copyLogs = "Копировать журналы"
    override val clearLogs = "Очистить журналы"
    override val logsCopiedToClipboard = "Журналы скопированы в буфер обмена"

    // Configuration Info
    override val currentConfiguration = "Текущая конфигурация"
    override val provider = "Провайдер"
    override val transcriptionModel = "Модель расшифровки"
    override val postProcessingModel = "Модель пост-обработки"
    override val postProcessingModelDesc = "gpt-4o-mini (для не-verbatim режимов и перевода)"
    override val none = "Нет"
    override val keepOriginal = "оставить оригинал"
    override val notConfigured = "Не настроено"

    // Transcription History
    override val transcriptionHistory = "История расшифровок"
    override val historyCount = "{count}/20"
    override val noHistoryYet = "История пока пуста"
    override val clearAll = "ОЧИСТИТЬ ВСЁ"

    // Connection Test
    override val connectionTesting = "Проверка соединения..."
    override val connectionSuccess = "Соединение успешно! API отвечает."
    override val connectionFailed = "Ошибка соединения"
    override val authenticationFailed = "Ошибка аутентификации. Проверьте ваш ключ API."
    override val endpointNotFound = "Эндпоинт не найден. Проверьте базовый URL и ID модели."
    override val connectionTimeout = "Тайм-аут соединения. Проверьте ваше интернет-соединение."
    override val sslError = "Ошибка SSL/TLS. Проверьте URL эндпоинта (https)."

    // Errors
    override val error = "Ошибка"
    override val copyError = "КОПИРОВАТЬ ОШИБКУ"
    override val openSettings = "ОТКРЫТЬ НАСТРОЙКИ"
    override val dismiss = "ЗАКРЫТЬ"
    override val errorConfigureApiKey = "Пожалуйста, настройте ключ API в настройках"
    override val errorNoModeSelected = "Голосовой режим не выбран"
    override val errorRecordingFailed = "Ошибка записи"
    override val errorNetworkFailed = "Ошибка сети. Пожалуйста, проверьте ваше соединение."
    override val errorApiCall = "Ошибка API"
    override val errorPermissionMicrophone = "Разрешение на микрофон не предоставлено. Пожалуйста, включите доступ к микрофону в настройках Android."
    override val errorMicrophoneInUse = "Нет доступа к микрофону. Возможно, он используется другим приложением."

    // Processing Info Toast
    override val translated = "Переведено на"
    override val twoStepProcessing = "Двухэтапная обработка"

    // Time units
    override val minutes = "м"
    override val seconds = "с"

    // Input Field Information
    override val inputFieldType = "Тип"
    override val inputFieldApp = "Приложение"
    override val inputFieldAction = "Действие"
    override val fieldTypeText = "Текст"
    override val fieldTypeEmail = "Email"
    override val fieldTypePassword = "Пароль"
    override val fieldTypeNumber = "Число"
    override val fieldTypePhone = "Телефон"
    override val fieldTypeUrl = "URL"
    override val fieldTypeMultiline = "Многострочный"
    override val fieldTypeUnknown = "Неизвестно"
    override val actionNone = "Нет"
    override val actionDone = "Готово"
    override val actionGo = "Перейти"
    override val actionSearch = "Поиск"
    override val actionSend = "Отправить"
    override val actionNext = "Далее"
    override val actionPrevious = "Назад"

    // Usage Guide (About Screen)
    override val usageGuideTitle = "Как использовать"
    override val voiceModesGuide = "Голосовые режимы"
    override val voiceModeVerbatimDesc = "Точная копия — Точная расшифровка как произнесено"
    override val voiceModeFixGrammarDesc = "Исправить грамматику — Исправляет грамматику и орфографию"
    override val voiceModePoliteDesc = "Вежливый — Делает речь профессиональной и дружелюбной"
    override val voiceModePromptFormatterDesc = "Форматировщик промптов — Оптимизирует текст для AI-промптов"
    override val voiceModeLlmResponseDesc = "Ответ LLM — Получайте прямые ответы на вопросы"
    override val voiceModeConfigurationDesc = "Конфигурация — Управляйте настройками голосом"
    override val configurationModeTitle = "Режим конфигурации"
    override val configurationModeDesc = "Переключитесь на режим «Конфигурация» для управления настройками голосовыми командами. Когда вы произнесёте команду, появится диалог подтверждения с описанием изменения."
    override val sampleVoiceCommandsTitle = "Примеры голосовых команд"
    override val sampleCommandLanguage = "«Смени язык ввода на испанский» / «Переведи на французский»"
    override val sampleCommandMode = "«Смени режим на точную копию» / «Включи исправление грамматики»"
    override val sampleCommandTheme = "«Включи тёмный режим» / «Используй светлую тему» / «Следовать системной теме»"
    override val sampleCommandHistory = "«Включи историю» / «Выключи историю»"
    override val sampleCommandDeveloper = "«Включи режим разработчика» / «Выключи техно-режим»"
    override val sampleCommandInterface = "«Смени интерфейс на русский» / «Установи язык UI на арабский»"
    override val sampleCommandExit = "«Выйти из режима конфигурации» / «Отключить командный режим»"
    override val howItWorksTitle = "Как это работает"
    override val howItWorksStep1 = "1. Выберите «Конфигурация» в селекторе режимов"
    override val howItWorksStep2 = "2. Нажмите на микрофон и произнесите команду"
    override val howItWorksStep3 = "3. Просмотрите изменение в диалоге подтверждения"
    override val howItWorksStep4 = "4. Нажмите «Применить» для подтверждения или «Отмена» для отклонения"
    override val howItWorksConfirmation = "После подтверждения вы увидите уведомление об обновлении настройки."
    override val deleteButtonTitle = "Кнопка удаления"
    override val deleteButtonTap = "Нажатие — Удалить один символ (или выделенный текст)"
    override val deleteButtonHold = "Удержание — Непрерывное удаление"
    override val deleteButtonLongHold = "Удержание 5 секунд — Удалить ВЕСЬ текст (кнопка станет красной)"
    override val languageSelectionTitle = "Выбор языка"
    override val languageSelectionDesc = "Используйте режим конфигурации для смены языков без рук, или нажмите на кнопки языков под микрофоном для выбора из списка."

    // Settings categories
    override val categoryTranscriptionTitle = "Распознавание"
    override val categoryTranscriptionSubtitle = "Провайдер, модель, языки"
    override val categoryPostProcessingTitle = "Постобработка"
    override val categoryPostProcessingSubtitle = "LLM для преобразований и перевода"
    override val categoryLocalModelsTitle = "Локальные модели"
    override val categoryLocalModelsSubtitle = "Загрузка моделей Whisper + Gemma на устройство"
    override val categoryVoiceModesTitle = "Режимы голоса"
    override val categoryVoiceModesSubtitle = "Пользовательские подсказки для расшифровок"
    override val categoryKeyboardBehaviorTitle = "Клавиатура и поведение"
    override val categoryKeyboardBehaviorSubtitle = "История, буфер обмена, аудиофайлы"
    override val categoryAppearanceTitle = "Внешний вид"
    override val categoryAppearanceSubtitle = "Тема, шрифты, язык интерфейса"
    override val categoryAdvancedTitle = "Дополнительно"
    override val categoryAdvancedSubtitle = "Логи, интеграции, диагностика"
    override val categoryAboutTitle = "О приложении"
    override val categoryAboutSubtitle = "Авторы, лицензия, версия"

    // About stats
    override val statsAudioTranscribedLabel = "Распознано аудио"
    override val statsTextWrittenLabel = "Написано текста"
    override val statsTypingTimeSavedLabel = "Примерно сэкономлено времени набора при 200 зн/мин"

    // Settings overflow + advanced detail
    override val settingsOverflowAbout = "О приложении"
    override val settingsOverflowExportSecrets = "Экспортировать секреты"
    override val settingsOverflowMoreDesc = "Ещё"
    override val settingsActivePrefix = "Активно: "
    override val settingsSecretsCopiedToast = "Секреты скопированы в буфер обмена"
    override val advancedApiLogsTitle = "Журналы вызовов API"
    override val advancedApiLogsDescription = "Просмотр недавних запросов транскрипции и LLM"
    override val advancedProviderKeyHelpTitle = "Помощь с API-ключом провайдера"
    override val advancedProviderKeyHelpDescription = "Как получить API-ключ для текущего провайдера"
    override val advancedExportSecretsTitle = "Экспорт секретов в буфер обмена"
    override val advancedExportSecretsDescription = "Копирует все ключи и эндпоинты провайдеров в формате JSON"

    // Appearance section
    override val appearanceSectionColorHeader = "Цвет"
    override val appearanceDynamicColorTitle = "Динамические цвета"
    override val appearanceDynamicColorDescription = "Подбирать цвета под обои (Material You)"
    override val appearanceSectionThemeHeader = "Тема"
    override val appearanceSectionTypographyHeader = "Типографика"
    override val appearanceTextSizeLabel = "Размер текста"
    override val appearanceFontFamilyLabel = "Семейство шрифтов"
    override val appearanceSectionInterfaceLanguageHeader = "Язык интерфейса"

    // LLM config section
    override val llmLocalLlamacppHeader = "Локальный HTTP-сервер llama.cpp"
    override val llmLocalLlamacppDescription = "Сначала запустите сервер в Termux, затем HyperWhisper будет обращаться к нему по HTTP. URL по умолчанию рассчитан на конфигурацию llama-server без настроек: 127.0.0.1:8080."
    override val llmLocalLlamacppCommands = "Termux:  pkg install llama-cpp\n         llama-server -m /sdcard/LLM/<model>.gguf"
    override val llmLocalLlamacppModelHint = "Model ID ниже должен совпадать с именем модели, которое сообщает llama-server (обычно имя GGUF-файла без расширения или то, что передано в --alias)."
    override val llmLocalGemmaHeader = "Встроенный MediaPipe LLM"
    override val llmLocalGemmaActiveModelPrefix = "Модель: "
    override val llmLocalGemmaNoModelHint = "Модель Gemma не выбрана. Выберите .bin, сконвертированный для MediaPipe (litert-community на HuggingFace), в разделе «Транскрипция → Локально». Файлы GGUF не загружаются."
    override val llmLocalGemmaOnDeviceNote = "Работает полностью на устройстве. Внешний сервер не нужен."
    override val llmConfigBaseUrlLabel = "Базовый URL LLM"
    override val llmConfigBaseUrlSupportingText = "API-эндпоинт для LLM постобработки"
    override val llmConfigNoApiKeyRequired = "API-ключ не требуется"
    override val llmConfigApiKeyLabel = "API-ключ LLM"
    override val llmConfigApiKeyPlaceholder = "Введите API-ключ для провайдера LLM"
    override val llmConfigUseTranscriptionKey = "Использовать ключ этого провайдера из «Транскрипции»"
    override val llmConfigReuseKeyForTranscription = "Использовать этот ключ для провайдера транскрипции"
    override val llmConfigModelInfoDesc = "Информация о модели LLM"
    override val llmConfigUsageInfo = "Этот LLM используется для постобработки (вежливый, неформальный и т. д.) и перевода. Не применяется в дословном режиме."
    override val llmConfigTestPostProcessing = "Проверить постобработку с примером текста"
    override val llmConfigTestRunningPlaceholder = "Отправка примера текста в LLM…"
    override val llmConfigDisabledNote = "Постобработка отключена. Доступна только дословная транскрипция."

    // Keyboard behavior section
    override val keyboardBehaviorHistoryHeader = "История"
    override val keyboardBehaviorEnableHistoryDescription = "Долгое нажатие на кнопку вставки покажет последние транскрипции"
    override val keyboardBehaviorUnlimitedHistoryTitle = "Неограниченная история"
    override val keyboardBehaviorUnlimitedHistoryDescription = "Хранить все транскрипции (используется больше памяти)"
    override val keyboardBehaviorClipboardAudioHeader = "Буфер обмена и аудио"
    override val keyboardBehaviorAutoCopyDescription = "Автоматически копировать каждую транскрипцию"
    override val keyboardBehaviorSaveAudioTitle = "Сохранять оригинальное аудио"
    override val keyboardBehaviorSaveAudioDescription = "Сохранять записи для воспроизведения и повторной обработки"
    override val keyboardBehaviorKeyboardHeader = "Клавиатура"
    override val keyboardBehaviorShowSwitcherTitle = "Показывать переключатель клавиатуры"
    override val keyboardBehaviorShowSwitcherDescription = "Кнопка смены метода ввода рядом с выбором режима"
    override val keyboardBehaviorPerAppLayoutTitle = "Память раскладки по приложениям"
    override val keyboardBehaviorPerAppLayoutDescription = "Восстанавливать последнюю раскладку для каждого приложения (например, Code в Termux, Voice в WhatsApp)"
    override val keyboardBehaviorCodingAgentsHeader = "Кодинг-агенты"
    override val keyboardBehaviorCodingAgentsDescription = "Добавьте клавиатуры быстрых команд для CLI-агентов. Каждый включённый агент появится отдельным режимом в выпадающем меню режимов клавиатуры."
    override val keyboardBehaviorAgentDescriptionPrefix = "Клавиатура быстрых команд для "
    override val keyboardBehaviorDeveloperHeader = "Разработчик"
    override val keyboardBehaviorTechieModeTitle = "Режим техника"
    override val keyboardBehaviorTechieModeDescription = "Показывать диагностическую информацию и кнопку журналов на клавиатуре"
    override val keyboardBehaviorMaxHistoryTitle = "Максимум элементов истории"
    override val keyboardBehaviorMaxHistoryRange = "Сколько хранить (1–100)"

    // Selectors
    override val selectorFontLabel = "Шрифт"
    override val selectorLanguageLabel = "Язык"
    override val selectorCustomModelTag = "Пользовательская модель"
    override val selectorFilterModelsLabel = "Фильтр моделей"
    override val selectorFreeFilterLabel = "Бесплатные"
    override val selectorNoMatchingModels = "Подходящих моделей нет"
    override val selectorLlmModelLabel = "Модель LLM"
    override val selectorLlmProviderLabel = "Провайдер LLM постобработки"
    override val selectorProviderLabel = "Выбрать провайдера"

    // Transcription section
    override val transcriptionTabCloud = "Облако"
    override val transcriptionTabLocal = "Локально"
    override val transcriptionTestButton = "Проверить транскрипцию"
    override val transcriptionTestingShort = "Проверка…"
    override val transcriptionPreparingTest = "Подготовка теста…"
    override val transcriptionWorkingPlaceholder = "Выполняется…"
    override val transcriptionTestSuccessLabel = "Успех"
    override val transcriptionTestFailedLabel = "Ошибка"
    override val transcriptionTestReadyLabel = "Готово"
    override val transcriptionTestLogCopied = "Журнал теста скопирован"
    override val transcriptionTestLogCopyDesc = "Копировать журнал"
    override val transcriptionTestLogDismissDesc = "Закрыть"
    override val transcriptionTestLogExpand = "Развернуть журнал"
    override val transcriptionTestLogCollapse = "Свернуть журнал"
    override val transcriptionCloudActiveText = "Облако — активный источник транскрипции."
    override val transcriptionCloudInactiveText = "Конфигурация облака сохранена, но не активна. Используйте её, чтобы переопределить локальную модель."
    override val transcriptionSetCloudActive = "Сделать облако активным"
    override val transcriptionFieldGroupModel = "Модель"
    override val transcriptionApiKeyRequiredHint = "Обязательно"
    override val transcriptionApiKeyOptionalHint = "Необязательно"
    override val transcriptionApiKeyHide = "Скрыть"
    override val transcriptionApiKeyShow = "Показать"
    override val transcriptionHowToGetKey = "Как получить ключ"
    override val transcriptionLanguagesHeader = "Языки"
    override val transcriptionInputLanguageLabel = "Язык ввода"
    override val transcriptionInputLanguageSupporting = "Язык речи (поддерживается автоопределение)"
    override val transcriptionOutputLanguageLabel = "Язык вывода"
    override val transcriptionOutputLanguageSupporting = "Перевод транскрипции (оставьте пустым, чтобы сохранить оригинал)"
    override val transcriptionApiEndpointLabel = "Эндпоинт API"
    override val transcriptionRequiresApiKey = "Требуется ключ API"
    override val transcriptionRequiresApiKeyDesc = "Отключите для самостоятельно размещённых серверов без аутентификации"
    override val transcriptionLocalActivePrefix = "Локальный Whisper активен: "
    override val transcriptionLocalInactiveText = "Выберите модель ниже — нажмите «Использовать эту модель», чтобы сделать её активным источником транскрипции."
    override val transcriptionStorageAccessRequired = "Требуется доступ к хранилищу"
    override val transcriptionStorageAccessDesc = "Чтобы находить модели в Загрузках и других общих папках"
    override val transcriptionGrantAccess = "Предоставить доступ"
    override val transcriptionWhisperModelsHeader = "Модели Whisper"
    override val transcriptionNoModelsFound = "Модели не найдены. Поместите файлы .bin или .gguf в Downloads/Models."
    override val transcriptionRescan = "Пересканировать"
    override val transcriptionRefreshAccess = "Обновить доступ"
    override val transcriptionPerformanceHeader = "Производительность"
    override val transcriptionAutoDiscoverTitle = "Автообнаружение"
    override val transcriptionAutoDiscoverDesc = "Сканировать стандартные папки на наличие файлов моделей"
    override val transcriptionThreadsTitle = "Потоки обработки"
    override val transcriptionThreadsDesc = "Больше = быстрее, выше расход батареи (1–16)"
    override val transcriptionVerifyIntegrityDesc = "Проверить целостность"
    override val transcriptionUseThisModel = "Использовать эту модель"
    override val transcriptionActiveBadge = "Активна"

    // Voice mode dialogs
    override val dialogVoiceModeNamePlaceholder = "напр., «Формальный»"
    override val dialogVoiceModePromptPlaceholder = "напр., Транскрибируй и сделай формальным"

    // Language info dialog
    override val dialogInputLanguageBody = "Эта настройка подсказывает модели распознавания речи, на каком языке говорят. «Автоопределение» хорошо работает в большинстве случаев, но указание конкретного языка может повысить точность:"
    override val dialogInputLanguageBullet1 = "• Для говорящих с сильным акцентом."
    override val dialogInputLanguageBullet2 = "• Для редких языков или диалектов."
    override val dialogInputLanguageBullet3 = "• В шумной обстановке."
    override val dialogInputLanguageFooter = "Если транскрипции неточны, попробуйте указать здесь свой родной язык."

    // Logs info dialog
    override val dialogLogsInfoBody = "HyperWhisper записывает все запросы и ответы API для отладки."
    override val dialogLogsInfoViewingHeader = "Просмотр журналов:"
    override val dialogLogsInfoViewing1 = "• Через ADB: adb logcat | grep HyperWhisper"
    override val dialogLogsInfoViewing2 = "• Установите приложение для просмотра logcat из Play Store"
    override val dialogLogsInfoViewing3 = "• Фильтруйте по: ChatCompletionStrategy, VoiceRepository"
    override val dialogLogsInfoLoggedHeader = "Что записывается:"
    override val dialogLogsInfoLogged1 = "• Детали запроса API (URL, модель, промпты)"
    override val dialogLogsInfoLogged2 = "• Статус и содержимое ответа"
    override val dialogLogsInfoLogged3 = "• Использование токенов (вход/выход/всего)"
    override val dialogLogsInfoLogged4 = "• Информация об аудиофайлах"
    override val dialogLogsInfoLogged5 = "• Сообщения об ошибках и трассировки"
    override val dialogLogsInfoNote = "Примечание: в журналах отображаются только первые 10 символов ключей API."

    // Model info dialog
    override val dialogModelInfoTitle = "Информация о модели"
    override val dialogModelInfoProviderPrefix = "Провайдер: "
    override val dialogModelInfoSelectedModelLabel = "Выбранная модель:"
    override val dialogModelInfoAvailableModelsLabel = "Доступные модели:"

    // Provider key instructions dialog
    override val dialogProviderKeyTitle = "Как получить ключ API"
    override val providerKeyOpenaiStep1 = "1. Откройте страницу:"
    override val providerKeyOpenaiStep2 = "2. Нажмите «Create new secret key»."
    override val providerKeyOpenaiStep3 = "3. Скопируйте ключ (начинается с sk-) и вставьте в поле «Ключ API»."
    override val providerKeyDeepgramStep1 = "1. Откройте страницу:"
    override val providerKeyDeepgramStep2 = "2. Создайте/выберите проект и откройте API Keys."
    override val providerKeyDeepgramStep3 = "3. Создайте ключ и вставьте его в «Ключ API»."
    override val providerKeyAssemblyStep1 = "1. Откройте страницу:"
    override val providerKeyAssemblyStep2 = "2. Перейдите в API Keys."
    override val providerKeyAssemblyStep3 = "3. Скопируйте ключ и вставьте в «Ключ API»."
    override val providerKeyGoogleCloudStep1 = "1. Откройте страницу:"
    override val providerKeyGoogleCloudStep2 = "2. Включите Speech-to-Text API для своего проекта."
    override val providerKeyGoogleCloudStep3 = "3. Создайте учётные данные и вставьте ключ/токен в «Ключ API»."
    override val providerKeyAwsStep1 = "1. Откройте консоль AWS:"
    override val providerKeyAwsStep2 = "2. Создайте IAM-ключ доступа с правами Transcribe."
    override val providerKeyAwsStep3 = "3. Используйте формат ключа вашего прокси/шлюза в поле «Ключ API»."
    override val providerKeyAzureStep1 = "1. Откройте страницу:"
    override val providerKeyAzureStep2 = "2. Создайте ресурс Speech и откройте Keys and Endpoint."
    override val providerKeyAzureStep3 = "3. Скопируйте ключ и задайте эндпоинт и «Ключ API»."
    override val providerKeyDeepseekStep1 = "1. Откройте страницу:"
    override val providerKeyDeepseekStep2 = "2. Создайте ключ API."
    override val providerKeyDeepseekStep3 = "3. Вставьте ключ в «Ключ API»."
    override val providerKeyMistralStep1 = "1. Откройте страницу:"
    override val providerKeyMistralStep2 = "2. Создайте новый ключ API."
    override val providerKeyMistralStep3 = "3. Вставьте ключ в «Ключ API»."
    override val providerKeyRevStep1 = "1. Откройте страницу:"
    override val providerKeyRevStep2 = "2. Создайте аккаунт и сгенерируйте токен доступа."
    override val providerKeyRevStep3 = "3. Вставьте токен в «Ключ API»."
    override val providerKeyGroqStep1 = "1. Откройте страницу:"
    override val providerKeyGroqStep2 = "2. Создайте ключ API."
    override val providerKeyGroqStep3 = "3. Вставьте в «Ключ API»."
    override val providerKeyOpenrouterStep1 = "1. Откройте страницу:"
    override val providerKeyOpenrouterStep2 = "2. Создайте ключ."
    override val providerKeyOpenrouterStep3 = "3. Вставьте в «Ключ API»."
    override val providerKeyGeminiStep1 = "1. Откройте страницу:"
    override val providerKeyGeminiStep2 = "2. Создайте ключ API."
    override val providerKeyGeminiStep3 = "3. Вставьте в «Ключ API»."
    override val providerKeyAntigravityStep1 = "1. Используйте OAuth-доступ Google для повторного использования доступной квоты."
    override val providerKeyAntigravityStep2 = "2. Укажите Base URL эндпоинта Antigravity."
    override val providerKeyAntigravityStep3 = "3. Оставьте ключ API отключённым, если ваш шлюз его не требует."
    override val providerKeyHuggingfaceStep1 = "1. Откройте страницу:"
    override val providerKeyHuggingfaceStep2 = "2. Создайте токен доступа."
    override val providerKeyHuggingfaceStep3 = "3. Вставьте токен в «Ключ API»."
    override val providerKeySelfhostedStep1 = "1. Запустите локальный или удалённый сервер whisper.cpp."
    override val providerKeySelfhostedStep2 = "2. Укажите URL сервера в Base URL (для локального по умолчанию используйте http://127.0.0.1:8080/)."
    override val providerKeySelfhostedStep3 = "3. Если на шлюзе включена аутентификация, вставьте токен в «Ключ API»."
    override val providerKeyLocalStep1 = "1. Локальной обработке ключ API не нужен."
    override val providerKeyLocalStep2 = "2. Скачайте модель whisper.cpp (.bin) и положите её на устройство."
    override val providerKeyLocalStep3 = "3. Перейдите в раздел «Локальные модели», чтобы отсканировать и выбрать файл модели."

    // History reduction dialog
    override val dialogHistoryReductionTitle = "Уменьшить размер истории?"
    override val dialogHistoryReductionBodyFormat = "Вы уменьшаете максимальный размер истории с %1\$d до %2\$d элементов."
    override val dialogHistoryReductionWarningFormat = "%1\$d элементов истории вместе с их аудиофайлами будут удалены безвозвратно."
    override val dialogHistoryReductionUndoNote = "Это действие нельзя отменить."
    override val dialogHistoryReductionConfirmFormat = "УДАЛИТЬ %1\$d ЭЛЕМЕНТОВ"

    // API call logs screen
    override val apiCallLogsHeader = "ЖУРНАЛ ВЫЗОВОВ API"
    override val apiCallLogsSubtitle = "Просмотр недавних вызовов API"
    override val apiCallLogsStatistics = "Статистика"
    override val apiCallLogsStatTotal = "Всего вызовов"
    override val apiCallLogsStatSuccess = "Успешно"
    override val apiCallLogsStatErrors = "Ошибок"
    override val apiCallLogsStatAvgTime = "Среднее время"
    override val apiCallLogsEmpty = "Пока нет записанных вызовов API"
    override val apiCallLogsErrorPrefix = "Ошибка: "
    override val apiCallLogsSuccessDesc = "Успех"
    override val apiCallLogsErrorDesc = "Ошибка"

    // Language selector
    override val languageSelectorSearchPlaceholder = "Поиск языков..."

    // Keyboard accessibility & top strip
    override val keyboardDictationDesc = "Диктовка"
    override val keyboardBackspaceDesc = "Удалить"
    override val keyboardEnterDesc = "Ввод"
    override val keyboardSearchDesc = "Поиск"
    override val keyboardClearDesc = "Очистить"
    override val keyboardBackToVoiceDesc = "К голосу"
    override val keyboardLogsDesc = "Журналы"
    override val keyboardHelpDesc = "Справка"

    // Emoji keyboard
    override val emojiNoEmojisFound = "Эмодзи не найдены"
    override val emojiRecentlyUsed = "Недавние"
    override val emojiSearchPlaceholder = "Поиск эмодзи..."

    // Enum: LlmProvider displayName
    override val providerLlmNone = "Нет (только дословно)"
    override val providerLlmOpenai = "OpenAI"
    override val providerLlmDeepseek = "DeepSeek"
    override val providerLlmGemini = "Google Gemini"
    override val providerLlmAnthropic = "Anthropic Claude"
    override val providerLlmMistral = "Mistral AI"
    override val providerLlmGroq = "Groq"
    override val providerLlmOpenrouter = "OpenRouter"
    override val providerLlmOpenaiCompatible = "Совместимый с OpenAI"
    override val providerLlmLocalGemma = "Локальная Gemma"
    override val providerLlmLocalLlamacpp = "Локальный сервер llama.cpp"

    // Enum: ApiProvider displayName
    override val providerApiOpenai = "OpenAI Whisper"
    override val providerApiDeepgram = "Deepgram"
    override val providerApiAssemblyai = "AssemblyAI"
    override val providerApiGoogleCloud = "Google Cloud Speech"
    override val providerApiAwsTranscribe = "AWS Transcribe"
    override val providerApiAzureSpeech = "Azure AI Speech"
    override val providerApiDeepseek = "DeepSeek"
    override val providerApiMistral = "Mistral Voxtral"
    override val providerApiRevai = "Rev.ai"
    override val providerApiGroq = "Groq Whisper"
    override val providerApiOpenrouter = "OpenRouter"
    override val providerApiGemini = "Google Gemini"
    override val providerApiAntigravity = "Google Antigravity (OAuth)"
    override val providerApiHuggingface = "Hugging Face"
    override val providerApiSelfhostedWhisper = "Свой Whisper-сервер"
    override val providerApiLocalWhisper = "Локальный Whisper (.bin)"

    // Enum: ProcessingStage displayName
    override val processingStagePreparing = "Подготовка аудио..."
    override val processingStageConvertingAudio = "Преобразование аудио..."
    override val processingStageLoadingModel = "Загрузка модели..."
    override val processingStageTranscribing = "Распознавание..."
    override val processingStagePostProcessing = "Постобработка..."
    override val processingStageUploading = "Загрузка аудио..."
    override val processingStageWaitingApi = "Ожидание API..."
    override val processingStageFinishing = "Завершение..."

    // Enum: ColorSchemeOption displayName
    override val themeTerminalDark = "Тёмный терминал"
    override val themeOceanDeep = "Глубины океана"
    override val themeForestNight = "Лесная ночь"
    override val themeSunsetHorizon = "Закатный горизонт"
    override val themeArcticFrost = "Арктический иней"
    override val themeDesertStorm = "Песчаная буря"
    override val themeNeonCity = "Неоновый город"
    override val themeCherryBlossom = "Сакура"
    override val themeMidnightSky = "Полуночное небо"
    override val themeLavaFlow = "Поток лавы"
    override val themeMistyMountain = "Туманные горы"
    override val themeAutumnLeaves = "Осенняя листва"
    override val themeProfessionalBlue = "Деловой синий"
    override val themeWarmEarth = "Тёплая земля"
    override val themeCoolSlate = "Холодный сланец"
    override val themeVibrantPurple = "Яркий пурпур"
    override val themeEmeraldGreen = "Изумрудный"
    override val themeRubyRed = "Рубиновый"

    // Enum: UIScaleOption displayName
    override val uiScaleVerySmall = "Очень мелкий"
    override val uiScaleSmall = "Мелкий"
    override val uiScaleMedium = "Средний"
    override val uiScaleLarge = "Крупный"
    override val uiScaleVeryLarge = "Очень крупный"

    // Enum: FontFamilyOption displayName
    override val fontFamilyDefault = "По умолчанию"
    override val fontFamilySerif = "С засечками"
    override val fontFamilySansSerif = "Без засечек"
    override val fontFamilyMonospace = "Моноширинный"
    override val fontFamilyCursive = "Рукописный"

    // Enum: KeyboardInputMode displayName
    override val keyboardModeDictation = "Голос"
    override val keyboardModeQwerty = "Текст"
    override val keyboardModeCode = "Код"
    override val keyboardModeEmoji = "Эмодзи"
    override val keyboardModeAgentClaudeCode = "Claude Code"
    override val keyboardModeAgentOpencode = "OpenCode"
    override val keyboardModeAgentGemini = "Gemini CLI"
    override val keyboardModeAgentCodex = "Codex CLI"
    override val keyboardModeSpecialChars = "Символы"
    override val keyboardModeSystemKeys = "Системные клавиши"
    override val keyboardModeVibeCoding = "Vibe Coding"
    override val keyboardModeNumpad = "Цифровая клавиатура"

    // Enum: KeyboardLayout displayName
    override val keyboardLayoutEnglish = "Английский"
    override val keyboardLayoutRussian = "Русский"
    override val keyboardLayoutSpanish = "Испанский"
    override val keyboardLayoutFrench = "Французский"
    override val keyboardLayoutGerman = "Немецкий"
    override val keyboardLayoutArabic = "Арабский"

    // Enum: EmojiCategory displayName
    override val emojiCategorySmileys = "Смайлики"
    override val emojiCategoryPeople = "Люди"
    override val emojiCategoryAnimals = "Животные"
    override val emojiCategoryFood = "Еда"
    override val emojiCategoryActivities = "Активности"
    override val emojiCategoryTravel = "Путешествия"
    override val emojiCategoryObjects = "Объекты"
    override val emojiCategorySymbols = "Символы"
    override val emojiCategoryFlags = "Флаги"

    // Processing indicator
    override val processingEstimatedTimeFormat = "Прибл: ~%d с"

    // Network errors
    override val errorForbidden = "Запрещено — проверьте права ключа."
    override val errorRateLimit = "Превышен лимит запросов — повторите попытку позже."
    override val errorUnknown = "Неизвестная ошибка"
    override val errorProcessingFailedFormat = "Ошибка обработки: %1\$s: %2\$s"

    // Local processing
    override val secretsGateRevealTitle = "Подтвердите, чтобы показать ключ API"
    override val secretsGateExportTitle = "Подтвердите экспорт секретов"
    override val secretsGateSubtitle = "Используйте блокировку устройства, чтобы продолжить"
    override val secretsGateNotEnrolledMessage = "Сначала настройте блокировку устройства"
    override val secretsGateUnavailableMessage = "Аутентификация устройства недоступна"

    override val errorLocalWhisperPathMissing = "Путь к локальной модели Whisper не настроен."
    override val errorLocalWhisperModelNotFoundFormat = "Локальная модель Whisper не найдена: %s"
    override val errorLocalWhisperEmptyResult = "Локальный Whisper не вернул текст. Попробуйте другую модель или более громкое аудио."
    override val errorLocalProcessingFailedFormat = "Сбой локальной обработки: %1\$s: %2\$s"
    override val errorLocalInferenceFailedFormat = "Сбой локального вывода: %1\$s: %2\$s"
}
